fides_INSERT INTO athletes VALUES ('1', 'AALERUD Katrine', 'AALERUD K');
fides_INSERT INTO athletes VALUES ('2', 'ABAD Nestor', 'ABAD N');
fides_INSERT INTO athletes VALUES ('3', 'ABAGNALE Giovanni', 'ABAGNALE G');
fides_INSERT INTO athletes VALUES ('4', 'ABALDE Alberto', 'ABALDE A');
fides_INSERT INTO athletes VALUES ('5', 'ABALDE Tamara', 'ABALDE T');
fides_INSERT INTO athletes VALUES ('6', 'ABALO Luc', 'ABALO L');
fides_INSERT INTO athletes VALUES ('7', 'ABAROA Cesar', 'ABAROA C');
fides_INSERT INTO athletes VALUES ('8', 'ABASS Abobakr', 'ABASS A');
fides_INSERT INTO athletes VALUES ('9', 'ABBAGNALE Vincenzo', 'ABBAGNALE V');
fides_INSERT INTO athletes VALUES ('10', 'ABBASALI Hamideh', 'ABBASALI H');
fides_INSERT INTO athletes VALUES ('11', 'ABBASOV Islam', 'ABBASOV I');
fides_INSERT INTO athletes VALUES ('12', 'ABBINGH Lois', 'ABBINGH L');
fides_INSERT INTO athletes VALUES ('13', 'ABBOT Emily', 'ABBOT E');
fides_INSERT INTO athletes VALUES ('14', 'ABBOTT Monica', 'ABBOTT M');
fides_INSERT INTO athletes VALUES ('15', 'ABDALLA Abubaker Haydar', 'ABDALLA AH');
fides_INSERT INTO athletes VALUES ('16', 'ABDALRASOOL Mohamed', 'ABDALRASOOL M');
fides_INSERT INTO athletes VALUES ('17', 'ABDEL LATIF Radwa', 'ABDEL LATIF R');
fides_INSERT INTO athletes VALUES ('18', 'ABDEL RAZEK Samy', 'ABDEL RAZEK S');
fides_INSERT INTO athletes VALUES ('19', 'ABDELAAL Mohamed', 'ABDELAAL M');
fides_INSERT INTO athletes VALUES ('20', 'ABDELAZIZ Abdalla', 'ABDELAZIZ A');
fides_INSERT INTO athletes VALUES ('21', 'ABDELAZIZ Farah', 'ABDELAZIZ F');
fides_INSERT INTO athletes VALUES ('22', 'ABDELAZIZ Feryal', 'ABDELAZIZ F');
fides_INSERT INTO athletes VALUES ('23', 'ABDELMAWGOUD Mohamed', 'ABDELMAWGOUD M');
fides_INSERT INTO athletes VALUES ('24', 'ABDELMOTTALEB Diaaeldin Kamal Gouda', 'ABDELMOTTALEB DKG');
fides_INSERT INTO athletes VALUES ('25', 'ABDELRAHMAN Ihab', 'ABDELRAHMAN I');
fides_INSERT INTO athletes VALUES ('26', 'ABDELSALAM Mohamed', 'ABDELSALAM M');
fides_INSERT INTO athletes VALUES ('27', 'ABDELSALAM Nour', 'ABDELSALAM N');
fides_INSERT INTO athletes VALUES ('28', 'ABDELWAHED Ahmed', 'ABDELWAHED A');
fides_INSERT INTO athletes VALUES ('29', 'ABDI Bashir', 'ABDI B');
fides_INSERT INTO athletes VALUES ('30', 'ABDIRAHMAN Abdi', 'ABDIRAHMAN A');
fides_INSERT INTO athletes VALUES ('31', 'ABDUL HADI Farah Ann', 'ABDUL HADI FA');
fides_INSERT INTO athletes VALUES ('32', 'ABDUL RAHMAN Kiria Tikanah', 'ABDUL RAHMAN KT');
fides_INSERT INTO athletes VALUES ('33', 'ABDUL RAZZAQ Fathimath Nabaaha', 'ABDUL RAZZAQ FN');
fides_INSERT INTO athletes VALUES ('34', 'ABDULHAMID Saud', 'ABDULHAMID S');
fides_INSERT INTO athletes VALUES ('35', 'ABDULJABBAR Ammar Riad', 'ABDULJABBAR AR');
fides_INSERT INTO athletes VALUES ('36', 'ABDULLAEV Gulomjon', 'ABDULLAEV G');
fides_INSERT INTO athletes VALUES ('37', 'ABDULLAEV Muminjon', 'ABDULLAEV M');
fides_INSERT INTO athletes VALUES ('38', 'ABDULLAH Rahmat Erwin', 'ABDULLAH RE');
fides_INSERT INTO athletes VALUES ('39', 'ABDULLAYEV Mahammad', 'ABDULLAYEV M');
fides_INSERT INTO athletes VALUES ('40', 'ABDULLIN Ilfat', 'ABDULLIN I');
fides_INSERT INTO athletes VALUES ('41', 'ABDULREDHA Mohamed', 'ABDULREDHA M');
fides_INSERT INTO athletes VALUES ('42', 'ABDURAIMOV Elnur', 'ABDURAIMOV E');
fides_INSERT INTO athletes VALUES ('43', 'ABDURAKHIMOV Rasuljon', 'ABDURAKHIMOV R');
fides_INSERT INTO athletes VALUES ('44', 'ABDURAKHMONOV Bekzod', 'ABDURAKHMONOV B');
fides_INSERT INTO athletes VALUES ('45', 'ABE Hifumi', 'ABE H');
fides_INSERT INTO athletes VALUES ('46', 'ABE Takatoshi', 'ABE T');
fides_INSERT INTO athletes VALUES ('47', 'ABE Uta', 'ABE U');
fides_INSERT INTO athletes VALUES ('48', 'ABEBE Mekides', 'ABEBE M');
fides_INSERT INTO athletes VALUES ('49', 'ABEDINI Mojtaba', 'ABEDINI M');
fides_INSERT INTO athletes VALUES ('50', 'ABEL Jennifer', 'ABEL J');
fides_INSERT INTO athletes VALUES ('51', 'ABELA Matthew', 'ABELA M');
fides_INSERT INTO athletes VALUES ('52', 'ABELVIK ROED Magnus', 'ABELVIK ROED M');
fides_INSERT INTO athletes VALUES ('53', 'ABEYSINGHE Matthew', 'ABEYSINGHE M');
fides_INSERT INTO athletes VALUES ('54', 'ABIAN Pablo', 'ABIAN P');
fides_INSERT INTO athletes VALUES ('55', 'ABICHA Mohammed', 'ABICHA M');
fides_INSERT INTO athletes VALUES ('56', 'ABICHT Lorena', 'ABICHT L');
fides_INSERT INTO athletes VALUES ('57', 'ABIDINE Abidine', 'ABIDINE A');
fides_INSERT INTO athletes VALUES ('58', 'ABLIAZIN Denis', 'ABLIAZIN D');
fides_INSERT INTO athletes VALUES ('59', 'ABNER', 'ABNER');
fides_INSERT INTO athletes VALUES ('60', 'ABOUD Hadel', 'ABOUD H');
fides_INSERT INTO athletes VALUES ('61', 'ABOUELKASSEM Alaaeldin', 'ABOUELKASSEM A');
fides_INSERT INTO athletes VALUES ('62', 'ABOUKE Nancy Genzel', 'ABOUKE NG');
fides_INSERT INTO athletes VALUES ('63', 'ABRAHAM Tadesse', 'ABRAHAM T');
fides_INSERT INTO athletes VALUES ('64', 'ABRAHAMS Rusten John', 'ABRAHAMS RJ');
fides_INSERT INTO athletes VALUES ('65', 'ABRAMS Aliyah', 'ABRAMS A');
fides_INSERT INTO athletes VALUES ('66', 'ABRAMS Jasmine', 'ABRAMS J');
fides_INSERT INTO athletes VALUES ('67', 'ABRAMYAN Benik', 'ABRAMYAN B');
fides_INSERT INTO athletes VALUES ('68', 'ABREU Diogo', 'ABREU D');
fides_INSERT INTO athletes VALUES ('69', 'ABRINES Alex', 'ABRINES A');
fides_INSERT INTO athletes VALUES ('70', 'ABROSIMOV Kirill', 'ABROSIMOV K');
fides_INSERT INTO athletes VALUES ('71', 'ABU RABEE Asma', 'ABU RABEE A');
fides_INSERT INTO athletes VALUES ('72', 'ABU RMILAH Wesam', 'ABU RMILAH W');
fides_INSERT INTO athletes VALUES ('73', 'ABUAKU Joshua', 'ABUAKU J');
fides_INSERT INTO athletes VALUES ('74', 'ABUJBARA Tala', 'ABUJBARA T');
fides_INSERT INTO athletes VALUES ('75', 'ACERENZA Domenico', 'ACERENZA D');
fides_INSERT INTO athletes VALUES ('76', 'ACETI Vladimir', 'ACETI V');
fides_INSERT INTO athletes VALUES ('77', 'ACEVEDO Javier', 'ACEVEDO J');
fides_INSERT INTO athletes VALUES ('78', 'ACHAB Jaouad', 'ACHAB J');
fides_INSERT INTO athletes VALUES ('79', 'ACHANTA Kamal', 'ACHANTA K');
fides_INSERT INTO athletes VALUES ('80', 'ACHE Ragnar', 'ACHE R');
fides_INSERT INTO athletes VALUES ('81', 'ACHILLEOS Georgios', 'ACHILLEOS G');
fides_INSERT INTO athletes VALUES ('82', 'ACHIUWA Precious', 'ACHIUWA P');
fides_INSERT INTO athletes VALUES ('83', 'ACHONWA Natalie', 'ACHONWA N');
fides_INSERT INTO athletes VALUES ('84', 'ACHOURI Haikel', 'ACHOURI H');
fides_INSERT INTO athletes VALUES ('85', 'ACIN Nikola', 'ACIN N');
fides_INSERT INTO athletes VALUES ('86', 'ACKERMANN Simone', 'ACKERMANN S');
fides_INSERT INTO athletes VALUES ('87', 'ACOSTA Briseida', 'ACOSTA B');
fides_INSERT INTO athletes VALUES ('88', 'ACOSTA FERNANDEZ Yasmani', 'ACOSTA FERNANDEZ Y');
fides_INSERT INTO athletes VALUES ('89', 'ACOSTA GIRALDO Valentina', 'ACOSTA GIRALDO V');
fides_INSERT INTO athletes VALUES ('90', 'ACOSTA Marcelo', 'ACOSTA M');
fides_INSERT INTO athletes VALUES ('91', 'ACUNA Yenny', 'ACUNA Y');
fides_INSERT INTO athletes VALUES ('92', 'ADACHI Kazuya', 'ADACHI K');
fides_INSERT INTO athletes VALUES ('93', 'ADACHI Seiya', 'ADACHI S');
fides_INSERT INTO athletes VALUES ('94', 'ADAM Amal', 'ADAM A');
fides_INSERT INTO athletes VALUES ('95', 'ADAM Constantin', 'ADAM C');
fides_INSERT INTO athletes VALUES ('96', 'ADAMEK Klaudia', 'ADAMEK K');
fides_INSERT INTO athletes VALUES ('97', 'ADAMKIEWICZ Patrycja', 'ADAMKIEWICZ P');
fides_INSERT INTO athletes VALUES ('98', 'ADAMS Liam', 'ADAMS L');
fides_INSERT INTO athletes VALUES ('99', 'ADAMS Paul', 'ADAMS P');
fides_INSERT INTO athletes VALUES ('100', 'ADAMS Taeyanna', 'ADAMS T');
fides_INSERT INTO athletes VALUES ('101', 'ADAMS Valerie', 'ADAMS V');
fides_INSERT INTO athletes VALUES ('102', 'ADAMUS Bartlomiej Stefan', 'ADAMUS BS');
fides_INSERT INTO athletes VALUES ('103', 'ADAR Yasemin', 'ADAR Y');
fides_INSERT INTO athletes VALUES ('104', 'ADEBAYO Bam', 'ADEBAYO B');
fides_INSERT INTO athletes VALUES ('105', 'ADEGOKE Enoch', 'ADEGOKE E');
fides_INSERT INTO athletes VALUES ('106', 'ADEKUOROYE Odunayo Folasade', 'ADEKUOROYE OF');
fides_INSERT INTO athletes VALUES ('107', 'ADEL Ibrahim', 'ADEL I');
fides_INSERT INTO athletes VALUES ('108', 'ADENIYI Aminat Oluwafunmilayo', 'ADENIYI AO');
fides_INSERT INTO athletes VALUES ('109', 'ADESOKAN Dorcas Ajoke', 'ADESOKAN DA');
fides_INSERT INTO athletes VALUES ('110', 'ADILKHANOVA Alina', 'ADILKHANOVA A');
fides_INSERT INTO athletes VALUES ('111', 'ADLERTEG Jonna', 'ADLERTEG J');
fides_INSERT INTO athletes VALUES ('112', 'ADLINGTON Sarah', 'ADLINGTON S');
fides_INSERT INTO athletes VALUES ('113', 'ADO Pauline', 'ADO P');
fides_INSERT INTO athletes VALUES ('114', 'ADOLF Balazs', 'ADOLF B');
fides_INSERT INTO athletes VALUES ('115', 'ADOMAVICIUS Aurimas', 'ADOMAVICIUS A');
fides_INSERT INTO athletes VALUES ('116', 'AEDO Yanara', 'AEDO Y');
fides_INSERT INTO athletes VALUES ('117', 'AERNOUDTS Violaine', 'AERNOUDTS V');
fides_INSERT INTO athletes VALUES ('118', 'AFANADOR Brian', 'AFANADOR B');
fides_INSERT INTO athletes VALUES ('119', 'AFONSO Paixao', 'AFONSO P');
fides_INSERT INTO athletes VALUES ('120', 'AFONSO Salome', 'AFONSO S');
fides_INSERT INTO athletes VALUES ('121', 'AFOUMBA Gilles Anthony', 'AFOUMBA GA');
fides_INSERT INTO athletes VALUES ('122', 'AFREMOVA Natalia', 'AFREMOVA N');
fides_INSERT INTO athletes VALUES ('123', 'AFRIAT Charlotte', 'AFRIAT C');
fides_INSERT INTO athletes VALUES ('124', 'AGADA Caleb', 'AGADA C');
fides_INSERT INTO athletes VALUES ('125', 'AGAHOZO Alphonsine', 'AGAHOZO A');
fides_INSERT INTO athletes VALUES ('126', 'AGARD Terrence', 'AGARD T');
fides_INSERT INTO athletes VALUES ('127', 'AGARIE Yuto', 'AGARIE Y');
fides_INSERT INTO athletes VALUES ('128', 'AGATSUMA Haruka', 'AGATSUMA H');
fides_INSERT INTO athletes VALUES ('129', 'AGBEGNENOU Clarisse', 'AGBEGNENOU C');
fides_INSERT INTO athletes VALUES ('130', 'AGERO Eden', 'AGERO E');
fides_INSERT INTO athletes VALUES ('131', 'AGGEFORS Mikael', 'AGGEFORS M');
fides_INSERT INTO athletes VALUES ('132', 'AGHAEIHAJIAGHA Soraya', 'AGHAEIHAJIAGHA S');
fides_INSERT INTO athletes VALUES ('133', 'AGHAMIROVA Zohra', 'AGHAMIROVA Z');
fides_INSERT INTO athletes VALUES ('134', 'AGHAMIRZAEIJENAGHRAD Ali', 'AGHAMIRZAEIJENAGH.');
fides_INSERT INTO athletes VALUES ('135', 'AGHASYAN Levon', 'AGHASYAN L');
fides_INSERT INTO athletes VALUES ('136', 'AGHAYEV Rafael', 'AGHAYEV R');
fides_INSERT INTO athletes VALUES ('137', 'AGIOMOR Ekerekeme', 'AGIOMOR E');
fides_INSERT INTO athletes VALUES ('138', 'AGIURGIUCULESE Alexandra', 'AGIURGIUCULESE A');
fides_INSERT INTO athletes VALUES ('139', 'AGRALI Yavuz', 'AGRALI Y');
fides_INSERT INTO athletes VALUES ('140', 'AGREBI Omar', 'AGREBI O');
fides_INSERT INTO athletes VALUES ('141', 'AGRUSTI Andrea', 'AGRUSTI A');
fides_INSERT INTO athletes VALUES ('142', 'AGUIAR Mayra', 'AGUIAR M');
fides_INSERT INTO athletes VALUES ('143', 'AGUILAR Ali', 'AGUILAR A');
fides_INSERT INTO athletes VALUES ('144', 'AGUILAR Andres', 'AGUILAR A');
fides_INSERT INTO athletes VALUES ('145', 'AGUILAR Evelis Jazmin', 'AGUILAR EJ');
fides_INSERT INTO athletes VALUES ('146', 'AGUINAGALDE AQUIZU Julen', 'AGUINAGALDE AQUIZU');
fides_INSERT INTO athletes VALUES ('147', 'AGUIRRE Eduardo', 'AGUIRRE E');
fides_INSERT INTO athletes VALUES ('148', 'AGUIRRE Erick', 'AGUIRRE E');
fides_INSERT INTO athletes VALUES ('149', 'AGUIRRE Unai', 'AGUIRRE U');
fides_INSERT INTO athletes VALUES ('150', 'AGUNDEZ GARCIA Gabriela', 'AGUNDEZ GARCIA G');
fides_INSERT INTO athletes VALUES ('151', 'AH TONG Marion Faustino', 'AH TONG MF');
fides_INSERT INTO athletes VALUES ('152', 'AHMAD Muhammad Isa', 'AHMAD MI');
fides_INSERT INTO athletes VALUES ('153', 'AHMED Aiman', 'AHMED A');
fides_INSERT INTO athletes VALUES ('154', 'AHMED ALI YUSUF Abdulla Essa', 'AHMED ALI YUSUF AE');
fides_INSERT INTO athletes VALUES ('155', 'AHMED Enas', 'AHMED E');
fides_INSERT INTO athletes VALUES ('156', 'AHMED Junayna', 'AHMED J');
fides_INSERT INTO athletes VALUES ('157', 'AHMED Mohamed', 'AHMED M');
fides_INSERT INTO athletes VALUES ('158', 'AHMED Mohammed', 'AHMED M');
fides_INSERT INTO athletes VALUES ('159', 'AHMED Samaa', 'AHMED S');
fides_INSERT INTO athletes VALUES ('160', 'AHN Joonsoo', 'AHN J');
fides_INSERT INTO athletes VALUES ('161', 'AHOUANWANOU Odile', 'AHOUANWANOU O');
fides_INSERT INTO athletes VALUES ('162', 'AHOURE Murielle', 'AHOURE M');
fides_INSERT INTO athletes VALUES ('163', 'AHSAN Mohammad', 'M AHSAN');
fides_INSERT INTO athletes VALUES ('164', 'AHSINGER Nicole', 'AHSINGER N');
fides_INSERT INTO athletes VALUES ('165', 'AHYE Michelle-Lee', 'AHYE ML');
fides_INSERT INTO athletes VALUES ('166', 'AI Yanhan', 'AI Y');
fides_INSERT INTO athletes VALUES ('167', 'AICARDI Matteo', 'AICARDI M');
fides_INSERT INTO athletes VALUES ('168', 'AICOBOAE Vlad', 'AICOBOAE V');
fides_INSERT INTO athletes VALUES ('169', 'AIGNER Hannes', 'AIGNER H');
fides_INSERT INTO athletes VALUES ('170', 'AILINCAI Adriana', 'AILINCAI A');
fides_INSERT INTO athletes VALUES ('171', 'AIMABLE Steven', 'AIMABLE S');
fides_INSERT INTO athletes VALUES ('172', 'AINAGULOV Mirambek', 'AINAGULOV M');
fides_INSERT INTO athletes VALUES ('173', 'AIOANI Marian', 'AIOANI M');
fides_INSERT INTO athletes VALUES ('174', 'AISAH Windy Cantika', 'AISAH WC');
fides_INSERT INTO athletes VALUES ('175', 'AIT DAOUD Kamel', 'AIT DAOUD K');
fides_INSERT INTO athletes VALUES ('176', 'AIT OUAGRAM Zied', 'AIT OUAGRAM Z');
fides_INSERT INTO athletes VALUES ('177', 'AIT SAID Samir', 'AIT SAID S');
fides_INSERT INTO athletes VALUES ('178', 'AITCHISON Holly', 'AITCHISON H');
fides_INSERT INTO athletes VALUES ('179', 'AIZAWA Akira', 'AIZAWA A');
fides_INSERT INTO athletes VALUES ('180', 'AJOMALE Bolade', 'AJOMALE B');
fides_INSERT INTO athletes VALUES ('181', 'AKAHO Himawari', 'AKAHO H');
fides_INSERT INTO athletes VALUES ('182', 'AKGUL Taha', 'AKGUL T');
fides_INSERT INTO athletes VALUES ('183', 'AKGUN Omer', 'AKGUN O');
fides_INSERT INTO athletes VALUES ('184', 'AKHAIMOVA Liliia', 'AKHAIMOVA L');
fides_INSERT INTO athletes VALUES ('185', 'AKHMADIEV Ildar', 'AKHMADIEV I');
fides_INSERT INTO athletes VALUES ('186', 'AKHMETOVA Tatyana', 'AKHMETOVA T');
fides_INSERT INTO athletes VALUES ('187', 'AKHTAR Muhammad Khalil', 'AKHTAR MK');
fides_INSERT INTO athletes VALUES ('188', 'AKIMENKO Mikhail', 'AKIMENKO M');
fides_INSERT INTO athletes VALUES ('189', 'AKINRADEWO Foluke', 'AKINRADEWO F');
fides_INSERT INTO athletes VALUES ('190', 'AKINYI Elizabeth', 'AKINYI E');
fides_INSERT INTO athletes VALUES ('191', 'AKKUS Mihrac', 'AKKUS M');
fides_INSERT INTO athletes VALUES ('192', 'AKMAL Nurul', 'AKMAL N');
fides_INSERT INTO athletes VALUES ('193', 'AKMATALIEV Ernazar', 'AKMATALIEV E');
fides_INSERT INTO athletes VALUES ('194', 'AKMENS Roberts', 'AKMENS R');
fides_INSERT INTO athletes VALUES ('195', 'AKOZ Simge Sebnem', 'AKOZ SS');
fides_INSERT INTO athletes VALUES ('196', 'AKTAS Ugur', 'AKTAS U');
fides_INSERT INTO athletes VALUES ('197', 'AL ADAWI Issa Samir Hamed', 'AL ADAWI ISH');
fides_INSERT INTO athletes VALUES ('198', 'AL AHRACH Ali', 'AL AHRACH A');
fides_INSERT INTO athletes VALUES ('199', 'AL ALAWI Mazoon', 'AL ALAWI M');
fides_INSERT INTO athletes VALUES ('200', 'AL BAWWAB Yazan', 'AL BAWWAB Y');
fides_INSERT INTO athletes VALUES ('201', 'AL FAIHAN Abdulrahman', 'AL FAIHAN A');
fides_INSERT INTO athletes VALUES ('202', 'AL HARTHI Barakat', 'AL HARTHI B');
fides_INSERT INTO athletes VALUES ('203', 'AL KHAFAJI Mohammed', 'AL KHAFAJI M');
fides_INSERT INTO athletes VALUES ('204', 'AL KHATRI Hamed', 'AL KHATRI H');
fides_INSERT INTO athletes VALUES ('205', 'AL MANWARI Bashair Obaid', 'AL MANWARI BO');
fides_INSERT INTO athletes VALUES ('206', 'AL OBAIDI Aker', 'AL OBAIDI A');
fides_INSERT INTO athletes VALUES ('207', 'AL RASHEDI Mansour', 'AL RASHEDI M');
fides_INSERT INTO athletes VALUES ('208', 'AL RUMAIHI Mohammed', 'AL RUMAIHI M');
fides_INSERT INTO athletes VALUES ('209', 'AL YAARI Ahmed', 'AL YAARI A');
fides_INSERT INTO athletes VALUES ('210', 'AL YASSIN Mazen Moutan', 'AL YASSIN MM');
fides_INSERT INTO athletes VALUES ('211', 'ALAKHVERDOVI Sakhil', 'ALAKHVERDOVI S');
fides_INSERT INTO athletes VALUES ('212', 'ALAME Haimro', 'ALAME H');
fides_INSERT INTO athletes VALUES ('213', 'ALAMIAN Nima', 'ALAMIAN N');
fides_INSERT INTO athletes VALUES ('214', 'ALAMRI Abdulelah', 'ALAMRI A');
fides_INSERT INTO athletes VALUES ('215', 'ALARIE Elissa', 'ALARIE E');
fides_INSERT INTO athletes VALUES ('216', 'ALARZA Fernando', 'ALARZA F');
fides_INSERT INTO athletes VALUES ('217', 'ALBA CASTILLO Rafael Yunier', 'ALBA CASTILLO RY');
fides_INSERT INTO athletes VALUES ('218', 'ALBARRACIN Matias', 'ALBARRACIN M');
fides_INSERT INTO athletes VALUES ('219', 'ALBAWARDI Zaid', 'ALBAWARDI Z');
fides_INSERT INTO athletes VALUES ('220', 'ALBAYRAK Vedat', 'ALBAYRAK V');
fides_INSERT INTO athletes VALUES ('221', 'ALBERS Felice', 'ALBERS F');
fides_INSERT INTO athletes VALUES ('222', 'ALBERTARRIO Agustina', 'ALBERTARRIO A');
fides_INSERT INTO athletes VALUES ('223', 'ALBICY Andrew', 'ALBICY A');
fides_INSERT INTO athletes VALUES ('224', 'ALBRECHT Samuel', 'ALBRECHT S');
fides_INSERT INTO athletes VALUES ('225', 'ALBRIKAN Feras', 'ALBRIKAN F');
fides_INSERT INTO athletes VALUES ('226', 'ALBUKHARI Amin', 'ALBUKHARI A');
fides_INSERT INTO athletes VALUES ('227', 'ALDABBAGH Yasmeen', 'ALDABBAGH Y');
fides_INSERT INTO athletes VALUES ('228', 'ALDASS Sanda', 'ALDASS S');
fides_INSERT INTO athletes VALUES ('229', 'ALDAWSARI Khalifah', 'ALDAWSARI K');
fides_INSERT INTO athletes VALUES ('230', 'ALDAWSARI Salem', 'ALDAWSARI S');
fides_INSERT INTO athletes VALUES ('231', 'ALDERSEY Olympia', 'ALDERSEY O');
fides_INSERT INTO athletes VALUES ('232', 'ALEGRE BIOSCA David', 'ALEGRE BIOSCA D');
fides_INSERT INTO athletes VALUES ('233', 'ALEKSANDROVA Ekaterina', 'ALEKSANDROVA E');
fides_INSERT INTO athletes VALUES ('234', 'ALEKSANDROVA Kseniia', 'ALEKSANDROVA K');
fides_INSERT INTO athletes VALUES ('235', 'ALEKSANYAN Artur', 'ALEKSANYAN A');
fides_INSERT INTO athletes VALUES ('236', 'ALEKSIC Maja', 'ALEKSIC M');
fides_INSERT INTO athletes VALUES ('237', 'ALEKSIC Milan', 'ALEKSIC M');
fides_INSERT INTO athletes VALUES ('238', 'ALEKSIIVA Maryna', 'ALEKSIIVA M');
fides_INSERT INTO athletes VALUES ('239', 'ALEKSIIVA Vladyslava', 'ALEKSIIVA V');
fides_INSERT INTO athletes VALUES ('240', 'ALEMANNO Maria Grazia', 'ALEMANNO MG');
fides_INSERT INTO athletes VALUES ('241', 'ALEMU Habitam', 'ALEMU H');
fides_INSERT INTO athletes VALUES ('242', 'ALESSIO Simone', 'ALESSIO S');
fides_INSERT INTO athletes VALUES ('243', 'ALEXANDER Kayla', 'ALEXANDER K');
fides_INSERT INTO athletes VALUES ('244', 'ALEXANDRI Anna-Maria', 'ALEXANDRI AM');
fides_INSERT INTO athletes VALUES ('245', 'ALEXANDRI Eirini', 'ALEXANDRI E');
fides_INSERT INTO athletes VALUES ('246', 'ALEXIUSSON Agnes', 'ALEXIUSSON A');
fides_INSERT INTO athletes VALUES ('247', 'ALEXUC CIURARIU Alin', 'ALEXUC CIURARIU A');
fides_INSERT INTO athletes VALUES ('248', 'ALFADHEL Abdulrahman', 'ALFADHEL A');
fides_INSERT INTO athletes VALUES ('249', 'ALFARAJ Salman', 'ALFARAJ S');
fides_INSERT INTO athletes VALUES ('250', 'ALFONSO DOMINGUEZ Loren Berto', 'ALFONSO DOMINGUEZ');
fides_INSERT INTO athletes VALUES ('251', 'ALGHANNAM Khalid', 'ALGHANNAM K');
fides_INSERT INTO athletes VALUES ('252', 'ALGOTSSON OSTHOLT Sara', 'ALGOTSSON OSTHOLT');
fides_INSERT INTO athletes VALUES ('253', 'ALHAMDDAN Abdullah', 'ALHAMDDAN A');
fides_INSERT INTO athletes VALUES ('254', 'ALHAMMADI Mohamed', 'ALHAMMADI M');
fides_INSERT INTO athletes VALUES ('255', 'ALHASSAN Ali', 'ALHASSAN A');
fides_INSERT INTO athletes VALUES ('256', 'ALHASSANE Ismael', 'ALHASSANE I');
fides_INSERT INTO athletes VALUES ('257', 'ALHINDAWI Odai Riyad Adel', 'ALHINDAWI ORA');
fides_INSERT INTO athletes VALUES ('258', 'ALHUMAYD Mahmoud Mohammed S', 'ALHUMAYD MMS');
fides_INSERT INTO athletes VALUES ('259', 'ALI Ali Merza', 'ALI AM');
fides_INSERT INTO athletes VALUES ('260', 'ALI Hasan', 'ALI H');
fides_INSERT INTO athletes VALUES ('261', 'ALI Laila', 'ALI L');
fides_INSERT INTO athletes VALUES ('262', 'ALI Mohamed', 'ALI M');
fides_INSERT INTO athletes VALUES ('263', 'ALI Mohamed', 'ALI M');
fides_INSERT INTO athletes VALUES ('264', 'ALI MOHAMED Souhra', 'ALI MOHAMED S');
fides_INSERT INTO athletes VALUES ('265', 'ALI Ramla Said Ahmed', 'ALI RSA');
fides_INSERT INTO athletes VALUES ('266', 'ALI Selin', 'ALI S');
fides_INSERT INTO athletes VALUES ('267', 'ALI ZADA Masomah', 'ALI ZADA M');
fides_INSERT INTO athletes VALUES ('268', 'ALIEV Mourad', 'ALIEV M');
fides_INSERT INTO athletes VALUES ('269', 'ALIKAJ Ahmad', 'ALIKAJ A');
fides_INSERT INTO athletes VALUES ('270', 'ALIMURADOVA Laman', 'ALIMURADOVA L');
fides_INSERT INTO athletes VALUES ('271', 'ALINE', 'ALINE');
fides_INSERT INTO athletes VALUES ('272', 'ALIPOV Alexey', 'ALIPOV A');
fides_INSERT INTO athletes VALUES ('273', 'ALIREZA Husein', 'ALIREZA H');
fides_INSERT INTO athletes VALUES ('274', 'ALIYEV Haji', 'ALIYEV H');
fides_INSERT INTO athletes VALUES ('275', 'ALIYEV Tayfur', 'ALIYEV T');
fides_INSERT INTO athletes VALUES ('276', 'ALIZADEH Dara', 'ALIZADEH D');
fides_INSERT INTO athletes VALUES ('277', 'ALIZADEH ZENOORIN Kimia', 'ALIZADEH ZENOORIN');
fides_INSERT INTO athletes VALUES ('278', 'AL-KAABI Fatimah Abbas Waheeb', 'AL-KAABI F');
fides_INSERT INTO athletes VALUES ('279', 'ALKANA Antonio', 'ALKANA A');
fides_INSERT INTO athletes VALUES ('280', 'AL-KANJARI Amur Salim Ramadhan', 'AL-KANJARI ASR');
fides_INSERT INTO athletes VALUES ('281', 'ALKASBEH Obada Mohammad Mustafa', 'ALKASBEH OMM');
fides_INSERT INTO athletes VALUES ('282', 'ALKHADRAWI Ali', 'ALKHADRAWI A');
fides_INSERT INTO athletes VALUES ('283', 'ALKHULAIF Ayman', 'ALKHULAIF A');
fides_INSERT INTO athletes VALUES ('284', 'ALLEMAND Julie', 'ALLEMAND J');
fides_INSERT INTO athletes VALUES ('285', 'ALLEN Bec', 'ALLEN B');
fides_INSERT INTO athletes VALUES ('286', 'ALLEN Bertram', 'ALLEN B');
fides_INSERT INTO athletes VALUES ('287', 'ALLEN Devon', 'ALLEN D');
fides_INSERT INTO athletes VALUES ('288', 'ALLEN Nathon', 'ALLEN N');
fides_INSERT INTO athletes VALUES ('289', 'ALLEN Nick', 'ALLEN N');
fides_INSERT INTO athletes VALUES ('290', 'ALLICOCK Keevin', 'ALLICOCK K');
fides_INSERT INTO athletes VALUES ('291', 'ALLIKVEE Martin', 'ALLIKVEE M');
fides_INSERT INTO athletes VALUES ('292', 'ALLMAN Valarie', 'ALLMAN V');
fides_INSERT INTO athletes VALUES ('293', 'ALMADA Thiago', 'ALMADA T');
fides_INSERT INTO athletes VALUES ('294', 'ALMANZA Rose Mary', 'ALMANZA RM');
fides_INSERT INTO athletes VALUES ('295', 'ALMAQABI Ahmed', 'ALMAQABI A');
fides_INSERT INTO athletes VALUES ('296', 'ALMAS Deniz', 'ALMAS D');
fides_INSERT INTO athletes VALUES ('297', 'ALMASATFA Abdel Rahman', 'ALMASATFA AR');
fides_INSERT INTO athletes VALUES ('298', 'ALMATROOSHI Yousuf', 'ALMATROOSHI Y');
fides_INSERT INTO athletes VALUES ('299', 'ALMEIDA Joao', 'ALMEIDA J');
fides_INSERT INTO athletes VALUES ('300', 'ALMEIDA Nathalia', 'ALMEIDA N');
fides_INSERT INTO athletes VALUES ('301', 'ALMEIDA Teresa', 'ALMEIDA T');
fides_INSERT INTO athletes VALUES ('302', 'ALMOSAWI Sayed Mohammed', 'ALMOSAWI SM');
fides_INSERT INTO athletes VALUES ('303', 'ALMUTAIRI Saeid', 'ALMUTAIRI S');
fides_INSERT INTO athletes VALUES ('304', 'ALNAJI Sami', 'ALNAJI S');
fides_INSERT INTO athletes VALUES ('305', 'AL-OBAIDLY Abdulaziz', 'AL-OBAIDLY A');
fides_INSERT INTO athletes VALUES ('306', 'ALOMRAN Nasser', 'ALOMRAN N');
fides_INSERT INTO athletes VALUES ('307', 'ALONSO Agostina', 'ALONSO A');
fides_INSERT INTO athletes VALUES ('308', 'ALONSO Alejandra', 'ALONSO A');
fides_INSERT INTO athletes VALUES ('309', 'ALONSO Alejandro', 'ALONSO A');
fides_INSERT INTO athletes VALUES ('310', 'ALONSO Luana', 'ALONSO L');
fides_INSERT INTO athletes VALUES ('311', 'ALOTHMANI Ala', 'ALOTHMANI A');
fides_INSERT INTO athletes VALUES ('312', 'ALQAHTANI Tahani', 'ALQAHTANI T');
fides_INSERT INTO athletes VALUES ('313', 'AL-RAIMI Yasameen', 'AL-RAIMI Y');
fides_INSERT INTO athletes VALUES ('314', 'ALRASHIDI Abdullah', 'ALRASHIDI A');
fides_INSERT INTO athletes VALUES ('315', 'ALRASHIDI Talal', 'ALRASHIDI T');
fides_INSERT INTO athletes VALUES ('316', 'ALRUBAIE Mohammed', 'ALRUBAIE M');
fides_INSERT INTO athletes VALUES ('317', 'AL-SADEQ Julyana', 'AL-SADEQ J');
fides_INSERT INTO athletes VALUES ('318', 'ALSALEEM Seraj Abdulrahim M', 'ALSALEEM SAM');
fides_INSERT INTO athletes VALUES ('319', 'ALSAMAHIJI Hasan', 'ALSAMAHIJI H');
fides_INSERT INTO athletes VALUES ('320', 'ALSAYYAD Husain', 'ALSAYYAD H');
fides_INSERT INTO athletes VALUES ('321', 'ALSHAHRANI Yasser', 'ALSHAHRANI Y');
fides_INSERT INTO athletes VALUES ('322', 'ALSHAMMARI Mudhawi', 'ALSHAMMARI M');
fides_INSERT INTO athletes VALUES ('323', 'ALTAYEV Altay', 'ALTAYEV A');
fides_INSERT INTO athletes VALUES ('324', 'ALTENBURG Lisa', 'ALTENBURG L');
fides_INSERT INTO athletes VALUES ('325', 'ALTENHUBER Louisa', 'ALTENHUBER L');
fides_INSERT INTO athletes VALUES ('326', 'ALTHEMAN Maria Suelen', 'ALTHEMAN MS');
fides_INSERT INTO athletes VALUES ('327', 'ALTO Gaston', 'ALTO G');
fides_INSERT INTO athletes VALUES ('328', 'ALTUHAYFAN Hamad', 'ALTUHAYFAN H');
fides_INSERT INTO athletes VALUES ('329', 'ALTUKHOV Pavlo', 'ALTUKHOV P');
fides_INSERT INTO athletes VALUES ('330', 'ALVARADO Luciana', 'ALVARADO L');
fides_INSERT INTO athletes VALUES ('331', 'ALVARADO Roberto', 'ALVARADO R');
fides_INSERT INTO athletes VALUES ('332', 'ALVAREZ Anita', 'ALVAREZ A');
fides_INSERT INTO athletes VALUES ('333', 'ALVAREZ AZNAR Eduardo', 'ALVAREZ AZNAR E');
fides_INSERT INTO athletes VALUES ('334', 'ALVAREZ Dario', 'ALVAREZ D');
fides_INSERT INTO athletes VALUES ('335', 'ALVAREZ Eddy', 'ALVAREZ E');
fides_INSERT INTO athletes VALUES ('336', 'ALVAREZ Jorge', 'ALVAREZ J');
fides_INSERT INTO athletes VALUES ('337', 'ALVAREZ Jorge', 'ALVAREZ J');
fides_INSERT INTO athletes VALUES ('338', 'ALVAREZ Lazaro', 'ALVAREZ L');
fides_INSERT INTO athletes VALUES ('339', 'ALVAREZ Luis', 'ALVAREZ L');
fides_INSERT INTO athletes VALUES ('340', 'ALVAREZ Luz', 'ALVAREZ L');
fides_INSERT INTO athletes VALUES ('341', 'ALVAREZ PIEDRAHITA Estefania', 'ALVAREZ PIEDRAHITA');
fides_INSERT INTO athletes VALUES ('342', 'ALVAREZ Santiago', 'ALVAREZ S');
fides_INSERT INTO athletes VALUES ('343', 'ALVES Dani', 'ALVES D');
fides_INSERT INTO athletes VALUES ('344', 'ALVES LOPES Marcia', 'ALVES LOPES M');
fides_INSERT INTO athletes VALUES ('345', 'ALWADI Mohammad', 'ALWADI M');
fides_INSERT INTO athletes VALUES ('346', 'AL-WIR Amro', 'AL-WIR A');
fides_INSERT INTO athletes VALUES ('347', 'ALY ELKAMASH Marwan', 'ALY ELKAMASH M');
fides_INSERT INTO athletes VALUES ('348', 'AL-YAMANI Mokhtar', 'AL-YAMANI M');
fides_INSERT INTO athletes VALUES ('349', 'ALYOUHA Yaqoub', 'ALYOUHA Y');
fides_INSERT INTO athletes VALUES ('350', 'ALZIGKOUZI KOMINEA Maria Elli Lela', 'ALZIGKOUZI KOMINEA');
fides_INSERT INTO athletes VALUES ('351', 'ALZINI Martina', 'ALZINI M');
fides_INSERT INTO athletes VALUES ('352', 'AMADOR Andrey', 'AMADOR A');
fides_INSERT INTO athletes VALUES ('353', 'AMAISTROAIE Madalina', 'AMAISTROAIE M');
fides_INSERT INTO athletes VALUES ('354', 'AMANKUL Abilkhan', 'AMANKUL A');
fides_INSERT INTO athletes VALUES ('355', 'AMARE Girmaw', 'AMARE G');
fides_INSERT INTO athletes VALUES ('356', 'AMARIS Cesar', 'AMARIS C');
fides_INSERT INTO athletes VALUES ('357', 'AMB Kim', 'AMB K');
fides_INSERT INTO athletes VALUES ('358', 'AMBAKA Willy', 'AMBAKA W');
fides_INSERT INTO athletes VALUES ('359', 'AMBALA Atuhaire Ogola', 'AMBALA AO');
fides_INSERT INTO athletes VALUES ('360', 'AMBROCIO GREIFO Pool Edinson', 'AMBROCIO GREIFO PE');
fides_INSERT INTO athletes VALUES ('361', 'AMDOUNI Morhad', 'AMDOUNI M');
fides_INSERT INTO athletes VALUES ('362', 'AMER Mohamed', 'AMER M');
fides_INSERT INTO athletes VALUES ('363', 'AMES David', 'AMES D');
fides_INSERT INTO athletes VALUES ('364', 'AMHA Selam', 'AMHA S');
fides_INSERT INTO athletes VALUES ('365', 'AMIALIUSIK Alena', 'AMIALIUSIK A');
fides_INSERT INTO athletes VALUES ('366', 'AMIHERE Laeticia', 'AMIHERE L');
fides_INSERT INTO athletes VALUES ('367', 'AMINE Myles Nazem', 'AMINE MN');
fides_INSERT INTO athletes VALUES ('368', 'AMIRI Nadiem', 'AMIRI N');
fides_INSERT INTO athletes VALUES ('369', 'AMIT', 'AMIT');
fides_INSERT INTO athletes VALUES ('370', 'AMOAH Christian', 'AMOAH C');
fides_INSERT INTO athletes VALUES ('371', 'AMOAH Joseph Paul', 'AMOAH JP');
fides_INSERT INTO athletes VALUES ('372', 'AMOE-TARRANT Charisma', 'AMOE-TARRANT C');
fides_INSERT INTO athletes VALUES ('373', 'AMONDE Andrew', 'AMONDE A');
fides_INSERT INTO athletes VALUES ('374', 'AMORES CARUA Jhonatan Javier', 'AMORES CARUA JJ');
fides_INSERT INTO athletes VALUES ('375', 'AMORIM TALESKA Eduarda', 'AMORIM TALESKA E');
fides_INSERT INTO athletes VALUES ('376', 'AMOROS Emile', 'AMOROS E');
fides_INSERT INTO athletes VALUES ('377', 'AMOS Nijel', 'AMOS N');
fides_INSERT INTO athletes VALUES ('378', 'AMRI Marwa', 'AMRI M');
fides_INSERT INTO athletes VALUES ('379', 'AMUKAMARA Promise', 'AMUKAMARA P');
fides_INSERT INTO athletes VALUES ('380', 'AMUSAN Tobi', 'AMUSAN T');
fides_INSERT INTO athletes VALUES ('381', 'AN Baul', 'AN B');
fides_INSERT INTO athletes VALUES ('382', 'AN Changi', 'AN C');
fides_INSERT INTO athletes VALUES ('383', 'AN Changrim', 'AN C');
fides_INSERT INTO athletes VALUES ('384', 'AN Heji', 'AN H');
fides_INSERT INTO athletes VALUES ('385', 'AN Hyejin', 'AN H');
fides_INSERT INTO athletes VALUES ('386', 'AN San', 'AN S');
fides_INSERT INTO athletes VALUES ('387', 'AN Sehyeon', 'AN S');
fides_INSERT INTO athletes VALUES ('388', 'AN Seulki', 'AN S');
fides_INSERT INTO athletes VALUES ('389', 'AN Seyoung', 'AN SY');
fides_INSERT INTO athletes VALUES ('390', 'ANA Andreea Beatrice', 'ANA AB');
fides_INSERT INTO athletes VALUES ('391', 'ANACAN Andrea', 'ANACAN A');
fides_INSERT INTO athletes VALUES ('392', 'ANAGNOSTOPOULOU Chrysoula', 'ANAGNOSTOPOULOU C');
fides_INSERT INTO athletes VALUES ('393', 'ANAGOZ Yasemin', 'ANAGOZ Y');
fides_INSERT INTO athletes VALUES ('394', 'ANANI Kwadjo', 'ANANI K');
fides_INSERT INTO athletes VALUES ('395', 'ANASTASAKIS Michail', 'ANASTASAKIS M');
fides_INSERT INTO athletes VALUES ('396', 'ANASTASSIOU Lucie', 'ANASTASSIOU L');
fides_INSERT INTO athletes VALUES ('397', 'ANCER Abraham', 'ANCER A');
fides_INSERT INTO athletes VALUES ('398', 'ANDERSEN Brooke', 'ANDERSEN B');
fides_INSERT INTO athletes VALUES ('399', 'ANDERSON Andy', 'ANDERSON A');
fides_INSERT INTO athletes VALUES ('400', 'ANDERSON Britany', 'ANDERSON B');
fides_INSERT INTO athletes VALUES ('401', 'ANDERSON Doneisha', 'ANDERSON D');
fides_INSERT INTO athletes VALUES ('402', 'ANDERSON Freya', 'ANDERSON F');
fides_INSERT INTO athletes VALUES ('403', 'ANDERSON Haley', 'ANDERSON H');
fides_INSERT INTO athletes VALUES ('404', 'ANDERSON Lachlan', 'ANDERSON L');
fides_INSERT INTO athletes VALUES ('405', 'ANDERSON Matthew', 'ANDERSON M');
fides_INSERT INTO athletes VALUES ('406', 'ANDERSON Shae', 'ANDERSON S');
fides_INSERT INTO athletes VALUES ('407', 'ANDERSON Yvonne', 'ANDERSON Y');
fides_INSERT INTO athletes VALUES ('408', 'ANDERSSON Jonna', 'ANDERSSON J');
fides_INSERT INTO athletes VALUES ('409', 'ANDERSSON Lasse', 'ANDERSSON L');
fides_INSERT INTO athletes VALUES ('410', 'ANDIA Mary Luz', 'ANDIA ML');
fides_INSERT INTO athletes VALUES ('411', 'ANDINO Kolohe', 'ANDINO K');
fides_INSERT INTO athletes VALUES ('412', 'ANDISON Bailey', 'ANDISON B');
fides_INSERT INTO athletes VALUES ('413', 'ANDO Elreen Ann', 'ANDO EA');
fides_INSERT INTO athletes VALUES ('414', 'ANDO Yuka', 'ANDO Y');
fides_INSERT INTO athletes VALUES ('415', 'ANDOH Mikiko', 'ANDOH M');
fides_INSERT INTO athletes VALUES ('416', 'ANDRADE Jordin', 'ANDRADE J');
fides_INSERT INTO athletes VALUES ('417', 'ANDRADE Rebeca', 'ANDRADE R');
fides_INSERT INTO athletes VALUES ('418', 'ANDRE Angelica', 'ANDRE A');
fides_INSERT INTO athletes VALUES ('419', 'ANDRE Sylvain', 'ANDRE S');
fides_INSERT INTO athletes VALUES ('420', 'ANDRE Thiago', 'ANDRE T');
fides_INSERT INTO athletes VALUES ('421', 'ANDREEV Bozhidar Dimitrov', 'ANDREEV BD');
fides_INSERT INTO athletes VALUES ('422', 'ANDREEVA Irina', 'ANDREEVA I');
fides_INSERT INTO athletes VALUES ('423', 'ANDREJCZYK Maria', 'ANDREJCZYK M');
fides_INSERT INTO athletes VALUES ('424', 'ANDREOLI Tatiana', 'ANDREOLI T');
fides_INSERT INTO athletes VALUES ('425', 'ANDRESSA', 'ANDRESSA');
fides_INSERT INTO athletes VALUES ('426', 'ANDRESSINHA', 'ANDRESSINHA');
fides_INSERT INTO athletes VALUES ('427', 'ANDREW Joshter', 'ANDREW J');
fides_INSERT INTO athletes VALUES ('428', 'ANDREW Michael', 'ANDREW M');
fides_INSERT INTO athletes VALUES ('429', 'ANDREWS Abby', 'ANDREWS A');
fides_INSERT INTO athletes VALUES ('430', 'ANDREWS Ellesse', 'ANDREWS E');
fides_INSERT INTO athletes VALUES ('431', 'ANDREWS-NAHU Kanah', 'ANDREWS-NAHU K');
fides_INSERT INTO athletes VALUES ('432', 'ANDRIANTSITOHAINA Eric Herman', 'ANDRIANTSITOHAINA');
fides_INSERT INTO athletes VALUES ('433', 'ANDRIANTSITOHAINA Tojonirina Alain', 'ANDRIANTSITOHAINA');
fides_INSERT INTO athletes VALUES ('434', 'ANDRODIAS Matthieu', 'ANDRODIAS M');
fides_INSERT INTO athletes VALUES ('435', 'ANDRULYTE Viktorija', 'ANDRULYTE V');
fides_INSERT INTO athletes VALUES ('436', 'ANDRUSENKO Veronika', 'ANDRUSENKO V');
fides_INSERT INTO athletes VALUES ('437', 'ANDUJAR Pablo', 'ANDUJAR P');
fides_INSERT INTO athletes VALUES ('438', 'ANESTOR Sabiana', 'ANESTOR S');
fides_INSERT INTO athletes VALUES ('439', 'ANGELA Ramsey', 'ANGELA R');
fides_INSERT INTO athletes VALUES ('440', 'ANGELDAL Filippa', 'ANGELDAL F');
fides_INSERT INTO athletes VALUES ('441', 'ANGELINA', 'ANGELINA');
fides_INSERT INTO athletes VALUES ('442', 'ANGHEL Roxana', 'ANGHEL R');
fides_INSERT INTO athletes VALUES ('443', 'ANGUAMEA Jesus', 'ANGUAMEA J');
fides_INSERT INTO athletes VALUES ('444', 'ANGULO Jesus', 'ANGULO J');
fides_INSERT INTO athletes VALUES ('445', 'ANGULO Ricardo', 'ANGULO R');
fides_INSERT INTO athletes VALUES ('446', 'ANGULO Yuliana', 'ANGULO Y');
fides_INSERT INTO athletes VALUES ('447', 'ANGYAL Daniel', 'ANGYAL D');
fides_INSERT INTO athletes VALUES ('448', 'ANKUDINOFF Ashlee', 'ANKUDINOFF A');
fides_INSERT INTO athletes VALUES ('449', 'ANNE Mame-Ibra', 'ANNE MI');
fides_INSERT INTO athletes VALUES ('450', 'ANNEN Jolanda', 'ANNEN J');
fides_INSERT INTO athletes VALUES ('451', 'ANOSHKIN Roman', 'ANOSHKIN R');
fides_INSERT INTO athletes VALUES ('452', 'ANSAH Owen', 'ANSAH O');
fides_INSERT INTO athletes VALUES ('453', 'ANSAH Sarfo', 'ANSAH S');
fides_INSERT INTO athletes VALUES ('454', 'ANSAH-PEPRAH Lucas', 'ANSAH-PEPRAH L');
fides_INSERT INTO athletes VALUES ('455', 'ANSELL Liam Paul', 'ANSELL LP');
fides_INSERT INTO athletes VALUES ('456', 'ANSHU Anshu', 'ANSHU A');
fides_INSERT INTO athletes VALUES ('457', 'ANSLEY Giselle', 'ANSLEY G');
fides_INSERT INTO athletes VALUES ('458', 'ANTILL Caleb', 'ANTILL C');
fides_INSERT INTO athletes VALUES ('459', 'ANTOGNELLI Quentin', 'ANTOGNELLI Q');
fides_INSERT INTO athletes VALUES ('460', 'ANTOMARCHI Kaliema', 'ANTOMARCHI K');
fides_INSERT INTO athletes VALUES ('461', 'ANTON Elizabeth', 'ANTON E');
fides_INSERT INTO athletes VALUES ('462', 'ANTONIA FERREIRA Jaqueline', 'ANTONIA FERREIRA J');
fides_INSERT INTO athletes VALUES ('463', 'ANTONIOU Kalia', 'ANTONIOU K');
fides_INSERT INTO athletes VALUES ('464', 'ANTONIOU Nikolas', 'ANTONIOU N');
fides_INSERT INTO athletes VALUES ('465', 'ANTONOVA Nataliia', 'ANTONOVA N');
fides_INSERT INTO athletes VALUES ('466', 'ANTONSEN Anders', 'ANTONSEN A');
fides_INSERT INTO athletes VALUES ('467', 'ANTONY', 'ANTONY');
fides_INSERT INTO athletes VALUES ('468', 'ANTONY Alex', 'ANTONY A');
fides_INSERT INTO athletes VALUES ('469', 'ANTOSOVA Lenka', 'ANTOSOVA L');
fides_INSERT INTO athletes VALUES ('470', 'ANTUNA Uriel', 'ANTUNA U');
fides_INSERT INTO athletes VALUES ('471', 'ANTUNOVIC Andela', 'ANTUNOVIC A');
fides_INSERT INTO athletes VALUES ('472', 'ANVEGARD Anna', 'ANVEGARD A');
fides_INSERT INTO athletes VALUES ('473', 'ANWARI Fahim', 'ANWARI F');
fides_INSERT INTO athletes VALUES ('474', 'ANYANACHO Elizabeth Oluchi', 'ANYANACHO EO');
fides_INSERT INTO athletes VALUES ('475', 'ANZANI Simone', 'ANZANI S');
fides_INSERT INTO athletes VALUES ('476', 'AOKI Chika', 'AOKI C');
fides_INSERT INTO athletes VALUES ('477', 'AOKI Masumi', 'AOKI M');
fides_INSERT INTO athletes VALUES ('478', 'AOKI Reona', 'AOKI R');
fides_INSERT INTO athletes VALUES ('479', 'AOKI Ryoma', 'AOKI R');
fides_INSERT INTO athletes VALUES ('480', 'AOKI Yukito', 'AOKI Y');
fides_INSERT INTO athletes VALUES ('481', 'AOKUSO Paulo', 'AOKUSO P');
fides_INSERT INTO athletes VALUES ('482', 'AOYAGI Koyo', 'AOYAGI K');
fides_INSERT INTO athletes VALUES ('483', 'AOYAMA Hanae', 'AOYAMA H');
fides_INSERT INTO athletes VALUES ('484', 'AOYAMA Shuko', 'AOYAMA S');
fides_INSERT INTO athletes VALUES ('485', 'APAK Esref', 'APAK E');
fides_INSERT INTO athletes VALUES ('486', 'APETZ Nadine', 'APETZ N');
fides_INSERT INTO athletes VALUES ('487', 'APITHY Bolade', 'APITHY B');
fides_INSERT INTO athletes VALUES ('488', 'APOLONIA Tiago', 'APOLONIA T');
fides_INSERT INTO athletes VALUES ('489', 'APOSTALON Anika', 'APOSTALON A');
fides_INSERT INTO athletes VALUES ('490', 'APPEL CHEUICHE Marcio', 'APPEL CHEUICHE M');
fides_INSERT INTO athletes VALUES ('491', 'APPEL Max', 'APPEL M');
fides_INSERT INTO athletes VALUES ('492', 'APPLE Zach', 'APPLE Z');
fides_INSERT INTO athletes VALUES ('493', 'APPS Olivia', 'APPS O');
fides_INSERT INTO athletes VALUES ('494', 'APRAHAMIAN Alain', 'APRAHAMIAN A');
fides_INSERT INTO athletes VALUES ('495', 'AQUILLA Adelaide', 'AQUILLA A');
fides_INSERT INTO athletes VALUES ('496', 'AQUINO Rckaela Maree Ramos', 'AQUINO RMR');
fides_INSERT INTO athletes VALUES ('497', 'AR RASYID Muhd Noor Firdaus', 'AR RASYID MNF');
fides_INSERT INTO athletes VALUES ('498', 'ARADILLAS Stefania', 'ARADILLAS S');
fides_INSERT INTO athletes VALUES ('499', 'ARAFI Rababe', 'ARAFI R');
fides_INSERT INTO athletes VALUES ('500', 'ARAGA Ryutaro', 'ARAGA R');
fides_INSERT INTO athletes VALUES ('501', 'ARAI Atsushi', 'ARAI A');
fides_INSERT INTO athletes VALUES ('502', 'ARAI Chizuru', 'ARAI C');
fides_INSERT INTO athletes VALUES ('503', 'ARAI Matsuri', 'ARAI M');
fides_INSERT INTO athletes VALUES ('504', 'ARAKAKI Maria Eduarda', 'ARAKAKI ME');
fides_INSERT INTO athletes VALUES ('505', 'ARAKAWA Ryuta', 'ARAKAWA R');
fides_INSERT INTO athletes VALUES ('506', 'ARAKI Erika', 'ARAKI E');
fides_INSERT INTO athletes VALUES ('507', 'ARAKI Kenta', 'ARAKI K');
fides_INSERT INTO athletes VALUES ('508', 'ARAKJI Nada', 'ARAKJI N');
fides_INSERT INTO athletes VALUES ('509', 'ARANA Guilherme', 'ARANA G');
fides_INSERT INTO athletes VALUES ('510', 'ARANCINI Zoe', 'ARANCINI Z');
fides_INSERT INTO athletes VALUES ('511', 'ARANDA Nathalee', 'ARANDA N');
fides_INSERT INTO athletes VALUES ('512', 'ARANGO ESTRADA Monica', 'ARANGO ESTRADA M');
fides_INSERT INTO athletes VALUES ('513', 'ARASHIRO Yukiya', 'ARASHIRO Y');
fides_INSERT INTO athletes VALUES ('514', 'ARATHOON PACAS Enrique Jose', 'ARATHOON PACAS EJ');
fides_INSERT INTO athletes VALUES ('515', 'ARAUJO Larissa', 'ARAUJO L');
fides_INSERT INTO athletes VALUES ('516', 'ARAYA Karen', 'ARAYA K');
fides_INSERT INTO athletes VALUES ('517', 'ARBE Joaquin', 'ARBE J');
fides_INSERT INTO athletes VALUES ('518', 'ARCANJO Geisa', 'ARCANJO G');
fides_INSERT INTO athletes VALUES ('519', 'ARCE Daniel', 'ARCE D');
fides_INSERT INTO athletes VALUES ('520', 'ARCEO Mariana', 'ARCEO M');
fides_INSERT INTO athletes VALUES ('521', 'ARCHIBALD Emanuel', 'ARCHIBALD E');
fides_INSERT INTO athletes VALUES ('522', 'ARCHIBALD Katie', 'ARCHIBALD K');
fides_INSERT INTO athletes VALUES ('523', 'ARCILA HURTADO Isabella', 'ARCILA HURTADO I');
fides_INSERT INTO athletes VALUES ('524', 'ARCOS POVEDA Paula', 'ARCOS POVEDA P');
fides_INSERT INTO athletes VALUES ('525', 'AREGAWI Berihu', 'AREGAWI B');
fides_INSERT INTO athletes VALUES ('526', 'AREIA Antonio', 'AREIA A');
fides_INSERT INTO athletes VALUES ('527', 'ARENAS Julio', 'ARENAS J');
fides_INSERT INTO athletes VALUES ('528', 'ARENAS Sandra Lorena', 'ARENAS SL');
fides_INSERT INTO athletes VALUES ('529', 'ARENDSE Kurt-Lee', 'ARENDSE KL');
fides_INSERT INTO athletes VALUES ('530', 'ARENHART Barbara', 'ARENHART B E');
fides_INSERT INTO athletes VALUES ('531', 'AREVALO ALCON Alberto', 'AREVALO ALCON A');
fides_INSERT INTO athletes VALUES ('532', 'AREVALO Carlos', 'AREVALO C');
fides_INSERT INTO athletes VALUES ('533', 'AREVALO Eider', 'AREVALO E');
fides_INSERT INTO athletes VALUES ('534', 'AREVALO Samantha', 'AREVALO S');
fides_INSERT INTO athletes VALUES ('535', 'ARFT Caroline', 'ARFT C');
fides_INSERT INTO athletes VALUES ('536', 'ARGYROPOULOS KANAKAKIS Stylianos', 'ARGYROPOULOS KANAK');
fides_INSERT INTO athletes VALUES ('537', 'ARIAS CASTANEDA Yeni Marcela', 'ARIAS CASTANEDA YM');
fides_INSERT INTO athletes VALUES ('538', 'ARIAS Gabriel', 'ARIAS G');
fides_INSERT INTO athletes VALUES ('539', 'ARIAS GUZMAN Luis Antonio', 'ARIAS GUZMAN LA');
fides_INSERT INTO athletes VALUES ('540', 'ARICAN Ferhat', 'ARICAN F');
fides_INSERT INTO athletes VALUES ('541', 'ARIKAN Okyanus', 'ARIKAN O');
fides_INSERT INTO athletes VALUES ('542', 'ARIKAN Polat Kemboi', 'ARIKAN PK');
fides_INSERT INTO athletes VALUES ('543', 'ARIMA Yumi', 'ARIMA Y');
fides_INSERT INTO athletes VALUES ('544', 'ARIOTO Valerie', 'ARIOTO V');
fides_INSERT INTO athletes VALUES ('545', 'ARISTARKHOV Anton', 'ARISTARKHOV A');
fides_INSERT INTO athletes VALUES ('546', 'ARISTOTELI Alexandra', 'ARISTOTELI A');
fides_INSERT INTO athletes VALUES ('547', 'ARIZA Oscar', 'ARIZA O');
fides_INSERT INTO athletes VALUES ('548', 'ARKANIA Gogita', 'ARKANIA G');
fides_INSERT INTO athletes VALUES ('549', 'ARMANTO Lizzie', 'ARMANTO L');
fides_INSERT INTO athletes VALUES ('550', 'ARMIT Elle', 'ARMIT E');
fides_INSERT INTO athletes VALUES ('551', 'ARMSTRONG Emily', 'ARMSTRONG E');
fides_INSERT INTO athletes VALUES ('552', 'ARMSTRONG Joseph', 'ARMSTRONG J');
fides_INSERT INTO athletes VALUES ('553', 'ARNAUS Adri', 'ARNAUS A');
fides_INSERT INTO athletes VALUES ('554', 'ARNDT Nikias', 'ARNDT N');
fides_INSERT INTO athletes VALUES ('555', 'ARNOLD Mackenzie', 'ARNOLD M');
fides_INSERT INTO athletes VALUES ('556', 'ARNOLD Maximilian', 'ARNOLD M');
fides_INSERT INTO athletes VALUES ('557', 'AROP Marco', 'AROP M');
fides_INSERT INTO athletes VALUES ('558', 'ARREDONDO Edgar', 'ARREDONDO E');
fides_INSERT INTO athletes VALUES ('559', 'ARREGUI Brian Agustin', 'ARREGUI BA');
fides_INSERT INTO athletes VALUES ('560', 'ARREY SOPHINA Ayuk Otay', 'ARREY SOPHINA AO');
fides_INSERT INTO athletes VALUES ('561', 'ARROYO Andres', 'ARROYO A');
fides_INSERT INTO athletes VALUES ('562', 'ARROYO Jarod', 'ARROYO J');
fides_INSERT INTO athletes VALUES ('563', 'ARSIC Jovana', 'ARSIC J');
fides_INSERT INTO athletes VALUES ('564', 'ARSOVIC Andrea', 'ARSOVIC A');
fides_INSERT INTO athletes VALUES ('565', 'ARTACHO del SOLAR Mariafe', 'ARTACHO del SOLAR');
fides_INSERT INTO athletes VALUES ('566', 'ARTAMONOV Mikhail', 'ARTAMONOV M');
fides_INSERT INTO athletes VALUES ('567', 'ARTENI Florin', 'ARTENI F');
fides_INSERT INTO athletes VALUES ('568', 'ARTERCHUK Alina', 'ARTERCHUK A');
fides_INSERT INTO athletes VALUES ('569', 'ARTINGSTALL Karriss', 'ARTINGSTALL K');
fides_INSERT INTO athletes VALUES ('570', 'ARTYMATA Eleni', 'ARTYMATA E');
fides_INSERT INTO athletes VALUES ('571', 'ARTYUKH Danil', 'ARTYUKH D');
fides_INSERT INTO athletes VALUES ('572', 'ARUNA Quadri', 'ARUNA Q');
fides_INSERT INTO athletes VALUES ('573', 'ARUNOVIC Zorana', 'ARUNOVIC Z');
fides_INSERT INTO athletes VALUES ('574', 'ARZANI Daniel', 'ARZANI D');
fides_INSERT INTO athletes VALUES ('575', 'ASAAD Man', 'ASAAD M');
fides_INSERT INTO athletes VALUES ('576', 'ASADAUSKAITE Laura', 'ASADAUSKAITE L');
fides_INSERT INTO athletes VALUES ('577', 'ASADOV Elchin', 'ASADOV E');
fides_INSERT INTO athletes VALUES ('578', 'ASAI Yu', 'ASAI Y');
fides_INSERT INTO athletes VALUES ('579', 'ASAMURA Hideto', 'ASAMURA H');
fides_INSERT INTO athletes VALUES ('580', 'ASANAU Dzmitry', 'ASANAU D');
fides_INSERT INTO athletes VALUES ('581', 'ASANO Sakiyo', 'ASANO S');
fides_INSERT INTO athletes VALUES ('582', 'ASENCIO Jairo', 'ASENCIO J');
fides_INSERT INTO athletes VALUES ('583', 'ASENOV Daniel Panev', 'ASENOV DP');
fides_INSERT INTO athletes VALUES ('584', 'ASENSIO Marco', 'ASENSIO M');
fides_INSERT INTO athletes VALUES ('585', 'ASGREEN Kasper', 'ASGREEN K');
fides_INSERT INTO athletes VALUES ('586', 'ASHBY Madison', 'ASHBY M');
fides_INSERT INTO athletes VALUES ('587', 'ASHER-SMITH Dina', 'ASHER-SMITH D');
fides_INSERT INTO athletes VALUES ('588', 'ASHIKAWA Urara', 'ASHIKAWA U');
fides_INSERT INTO athletes VALUES ('589', 'ASHMAWY Maggy', 'ASHMAWY M');
fides_INSERT INTO athletes VALUES ('590', 'ASHOK Aditi', 'ASHOK A');
fides_INSERT INTO athletes VALUES ('591', 'ASHOUR Emam', 'ASHOUR E');
fides_INSERT INTO athletes VALUES ('592', 'ASHRAM Linoy', 'ASHRAM L');
fides_INSERT INTO athletes VALUES ('593', 'ASIL Adem', 'ASIL A');
fides_INSERT INTO athletes VALUES ('594', 'ASKANI Bilal', 'ASKANI B');
fides_INSERT INTO athletes VALUES ('595', 'ASKEROV Aleksandr', 'ASKEROV A');
fides_INSERT INTO athletes VALUES ('596', 'ASLAN Yigit', 'ASLAN Y');
fides_INSERT INTO athletes VALUES ('597', 'ASLANYAN Karen', 'ASLANYAN K');
fides_INSERT INTO athletes VALUES ('598', 'ASLLANI Kosovare', 'ASLLANI K');
fides_INSERT INTO athletes VALUES ('599', 'ASP Yndiara', 'ASP Y');
fides_INSERT INTO athletes VALUES ('600', 'ASPANDIYAROVA Dina', 'ASPANDIYAROVA D');
fides_INSERT INTO athletes VALUES ('601', 'ASSADILOV Darkhan', 'ASSADILOV D');
fides_INSERT INTO athletes VALUES ('602', 'ASSAGHIR Mohamed', 'ASSAGHIR M');
fides_INSERT INTO athletes VALUES ('603', 'ASSAKALOV Rustam', 'ASSAKALOV R');
fides_INSERT INTO athletes VALUES ('604', 'ASSAR Khalid', 'ASSAR K');
fides_INSERT INTO athletes VALUES ('605', 'ASSAR Omar', 'ASSAR O');
fides_INSERT INTO athletes VALUES ('606', 'ASSELAH Sonia', 'ASSELAH S');
fides_INSERT INTO athletes VALUES ('607', 'ASTRUP Kim', 'ASTRUP K');
fides_INSERT INTO athletes VALUES ('608', 'ATATOU Wided', 'ATATOU W');
fides_INSERT INTO athletes VALUES ('609', 'ATAYEV Merdan', 'ATAYEV M');
fides_INSERT INTO athletes VALUES ('610', 'ATIENO Camilla', 'ATIENO C');
fides_INSERT INTO athletes VALUES ('611', 'ATKIN Sam', 'ATKIN S');
fides_INSERT INTO athletes VALUES ('612', 'ATKINS Ariel', 'ATKINS A');
fides_INSERT INTO athletes VALUES ('613', 'ATKINSON Alia', 'ATKINSON A');
fides_INSERT INTO athletes VALUES ('614', 'ATKINSON Nathaniel', 'ATKINSON N');
fides_INSERT INTO athletes VALUES ('615', 'ATLI Suleyman', 'ATLI S');
fides_INSERT INTO athletes VALUES ('616', 'ATRINAGHARCHI Reza', 'ATRINAGHARCHI R');
fides_INSERT INTO athletes VALUES ('617', 'ATSU Jonathan', 'ATSU J');
fides_INSERT INTO athletes VALUES ('618', 'ATSUMI Mana', 'ATSUMI M');
fides_INSERT INTO athletes VALUES ('619', 'AU Hoi Shun Stephanie', 'AU HSS');
fides_INSERT INTO athletes VALUES ('620', 'AUBAKIROV Miras', 'AUBAKIROV M');
fides_INSERT INTO athletes VALUES ('621', 'AUBOECK Felix', 'AUBOECK F');
fides_INSERT INTO athletes VALUES ('622', 'AUBRY David', 'AUBRY D');
fides_INSERT INTO athletes VALUES ('623', 'AUBRY David', 'AUBRY D');
fides_INSERT INTO athletes VALUES ('624', 'AUDA Patrik', 'AUDA P');
fides_INSERT INTO athletes VALUES ('625', 'AUDINET Manon', 'AUDINET M');
fides_INSERT INTO athletes VALUES ('626', 'AUFFARTH Sandra', 'AUFFARTH S');
fides_INSERT INTO athletes VALUES ('627', 'AUGER-ALIASSIME Felix', 'AUGER-ALIASSIME F');
fides_INSERT INTO athletes VALUES ('628', 'AUGUSTYN Rafal', 'AUGUSTYN R');
fides_INSERT INTO athletes VALUES ('629', 'AULAR SANABRIA Orluis Alberto', 'AULAR SANABRIA OA');
fides_INSERT INTO athletes VALUES ('630', 'AUSTIN Tyler', 'AUSTIN T');
fides_INSERT INTO athletes VALUES ('631', 'AVANCINI Henrique', 'AVANCINI H');
fides_INSERT INTO athletes VALUES ('632', 'AVERINA Arina', 'AVERINA A');
fides_INSERT INTO athletes VALUES ('633', 'AVERINA Dina', 'AVERINA D');
fides_INSERT INTO athletes VALUES ('634', 'AVILA MANCIA Julimar', 'AVILA MANCIA J');
fides_INSERT INTO athletes VALUES ('635', 'AVILA RAMIREZ Keyla Paola', 'AVILA RAMIREZ KP');
fides_INSERT INTO athletes VALUES ('636', 'AVILA SEGURA Ceiber David', 'AVILA SEGURA CD');
fides_INSERT INTO athletes VALUES ('637', 'AVOLA Giorgio', 'AVOLA G');
fides_INSERT INTO athletes VALUES ('638', 'AWANG Mohd Azizulhasni', 'AWANG MA');
fides_INSERT INTO athletes VALUES ('639', 'AWITI ALCARAZ Prisca', 'AWITI ALCARAZ P');
fides_INSERT INTO athletes VALUES ('640', 'AXELSEN Viktor', 'AXELSEN V');
fides_INSERT INTO athletes VALUES ('641', 'AYACHE Alexandre', 'AYACHE A');
fides_INSERT INTO athletes VALUES ('642', 'AYALA Derlys', 'AYALA D');
fides_INSERT INTO athletes VALUES ('643', 'AYASH Ahmed', 'AYASH A');
fides_INSERT INTO athletes VALUES ('644', 'AYDEMIR AKYOL Naz', 'AYDEMIR AKYOL N');
fides_INSERT INTO athletes VALUES ('645', 'AYIM Miranda', 'AYIM M');
fides_INSERT INTO athletes VALUES ('646', 'AYIVON Claire', 'AYIVON C');
fides_INSERT INTO athletes VALUES ('647', 'AYOUNI Abdessalem', 'AYOUNI A');
fides_INSERT INTO athletes VALUES ('648', 'AZAAD Julian Amado', 'AZAAD JA');
fides_INSERT INTO athletes VALUES ('649', 'AZAMATI-KWAKU Benjamin', 'AZAMATI-KWAKU B');
fides_INSERT INTO athletes VALUES ('650', 'AZEMIA Ned', 'AZEMIA N');
fides_INSERT INTO athletes VALUES ('651', 'AZEVEDO Ana Carolina', 'AZEVEDO AC');
fides_INSERT INTO athletes VALUES ('652', 'AZEVEDO Catia', 'AZEVEDO C');
fides_INSERT INTO athletes VALUES ('653', 'AZEVEDO Joao', 'AZEVEDO J');
fides_INSERT INTO athletes VALUES ('654', 'AZHIKANOV Nurkanat', 'AZHIKANOV N');
fides_INSERT INTO athletes VALUES ('655', 'AZISBEKOV Atabek', 'AZISBEKOV A');
fides_INSERT INTO athletes VALUES ('656', 'AZIZOVA Farida', 'AZIZOVA F');
fides_INSERT INTO athletes VALUES ('657', 'AZMY Nora', 'AZMY N');
fides_INSERT INTO athletes VALUES ('658', 'AZUERO Domenica', 'AZUERO D');
fides_INSERT INTO athletes VALUES ('659', 'AZUMA Rio', 'AZUMA R');
fides_INSERT INTO athletes VALUES ('660', 'AZUMA Sera', 'AZUMA S');
fides_INSERT INTO athletes VALUES ('661', 'AZURMENDI Clara', 'AZURMENDI C');
fides_INSERT INTO athletes VALUES ('662', 'B. Sai Praneeth', 'B S P');
fides_INSERT INTO athletes VALUES ('663', 'BA Houleye', 'BA H');
fides_INSERT INTO athletes VALUES ('664', 'BA MATRAF Nooran', 'BA MATRAF N');
fides_INSERT INTO athletes VALUES ('665', 'BAALLA Youness', 'BAALLA Y');
fides_INSERT INTO athletes VALUES ('666', 'BAATARKHUYAG Otgonbold', 'BAATARKHUYAG O');
fides_INSERT INTO athletes VALUES ('667', 'BAATARSUKH Chinzorig', 'BAATARSUKH C');
fides_INSERT INTO athletes VALUES ('668', 'BAATTH Simranjit Kaur', 'BAATTH SK');
fides_INSERT INTO athletes VALUES ('669', 'BAAUW Judy', 'BAAUW J');
fides_INSERT INTO athletes VALUES ('670', 'BABA Yudai', 'BABA Y');
fides_INSERT INTO athletes VALUES ('671', 'BABAMURATOVA Gulbadam', 'BABAMURATOVA G');
fides_INSERT INTO athletes VALUES ('672', 'BABAYEV Nazim', 'BABAYEV N');
fides_INSERT INTO athletes VALUES ('673', 'BABEK Tomas', 'BABEK T');
fides_INSERT INTO athletes VALUES ('674', 'BABINTSEVA Aleksandra', 'BABINTSEVA A');
fides_INSERT INTO athletes VALUES ('675', 'BABNIK Pia', 'BABNIK P');
fides_INSERT INTO athletes VALUES ('676', 'BABOVIC Anastasija', 'BABOVIC A');
fides_INSERT INTO athletes VALUES ('677', 'BABRIS Helvijs', 'BABRIS H');
fides_INSERT INTO athletes VALUES ('678', 'BACCI Lorenzo', 'BACCI L');
fides_INSERT INTO athletes VALUES ('679', 'BACCUS Keanu', 'BACCUS K');
fides_INSERT INTO athletes VALUES ('680', 'BACH Helena', 'BACH H');
fides_INSERT INTO athletes VALUES ('681', 'BACH Marta', 'BACH M');
fides_INSERT INTO athletes VALUES ('682', 'BACHA Aymen', 'BACHA A');
fides_INSERT INTO athletes VALUES ('683', 'BACHER Florian', 'BACHER F');
fides_INSERT INTO athletes VALUES ('684', 'BACHKOV Hovhannes', 'BACHKOV H');
fides_INSERT INTO athletes VALUES ('685', 'BACHMANN Alexander', 'BACHMANN A');
fides_INSERT INTO athletes VALUES ('686', 'BACHMANN Simon', 'BACHMANN S');
fides_INSERT INTO athletes VALUES ('687', 'BACMAGA Dominika', 'BACMAGA D');
fides_INSERT INTO athletes VALUES ('688', 'BACON Phoebe', 'BACON P');
fides_INSERT INTO athletes VALUES ('689', 'BACOSI Diana', 'BACOSI D');
fides_INSERT INTO athletes VALUES ('690', 'BADAWY Aly', 'BADAWY A');
fides_INSERT INTO athletes VALUES ('691', 'BADENHORST Nardus', 'BADENHORST N');
fides_INSERT INTO athletes VALUES ('692', 'BADLOE Kiran', 'BADLOE K');
fides_INSERT INTO athletes VALUES ('693', 'BADOSA Paula', 'BADOSA P');
fides_INSERT INTO athletes VALUES ('694', 'BAE Hyeyoon', 'BAE H');
fides_INSERT INTO athletes VALUES ('695', 'BAE Sanghee', 'BAE S');
fides_INSERT INTO athletes VALUES ('696', 'BAGNIS Facundo', 'BAGNIS F');
fides_INSERT INTO athletes VALUES ('697', 'BAH Mamadou', 'BAH M');
fides_INSERT INTO athletes VALUES ('698', 'BAH Mamadou Samba', 'BAH MS');
fides_INSERT INTO athletes VALUES ('699', 'BAHLOUL Ramzi', 'BAHLOUL R');
fides_INSERT INTO athletes VALUES ('700', 'BAHMANYAR Sara', 'BAHMANYAR S');
fides_INSERT INTO athletes VALUES ('701', 'BAHTA Meraf', 'BAHTA M');
fides_INSERT INTO athletes VALUES ('702', 'BAHUTSKI Yauheni', 'BAHUTSKI Y');
fides_INSERT INTO athletes VALUES ('703', 'BAI Li', 'BAI L');
fides_INSERT INTO athletes VALUES ('704', 'BAIG Adamyuki', 'BAIG A');
fides_INSERT INTO athletes VALUES ('705', 'BAILEY Sean', 'BAILEY S');
fides_INSERT INTO athletes VALUES ('706', 'BAILLEUL Margaux', 'BAILLEUL M');
fides_INSERT INTO athletes VALUES ('707', 'BAILLY Eric', 'BAILLY E');
fides_INSERT INTO athletes VALUES ('708', 'BAJIC Stefan', 'BAJIC S');
fides_INSERT INTO athletes VALUES ('709', 'BAJOR Natalia', 'BAJOR N');
fides_INSERT INTO athletes VALUES ('710', 'BAJRANG Bajrang', 'BAJRANG B');
fides_INSERT INTO athletes VALUES ('711', 'BAJWA Angad Vir Singh', 'BAJWA AVS');
fides_INSERT INTO athletes VALUES ('712', 'BAKER Georgia', 'BAKER G');
fides_INSERT INTO athletes VALUES ('713', 'BAKER Kurt', 'BAKER K');
fides_INSERT INTO athletes VALUES ('714', 'BAKER Nicklas', 'BAKER N');
fides_INSERT INTO athletes VALUES ('715', 'BAKER Perry', 'BAKER P');
fides_INSERT INTO athletes VALUES ('716', 'BAKER Ronnie', 'BAKER R');
fides_INSERT INTO athletes VALUES ('717', 'BAKI Abdullah Hel', 'BAKI AH');
fides_INSERT INTO athletes VALUES ('718', 'BAKKER Billy', 'BAKKER B');
fides_INSERT INTO athletes VALUES ('719', 'BAKSHI Gleb', 'BAKSHI G');
fides_INSERT INTO athletes VALUES ('720', 'BALADIN Hande', 'BALADIN H');
fides_INSERT INTO athletes VALUES ('721', 'BALANDIN Dmitriy', 'BALANDIN D');
fides_INSERT INTO athletes VALUES ('722', 'BALASTEGUI Manel', 'BALASTEGUI M');
fides_INSERT INTO athletes VALUES ('723', 'BALAZ Samuel', 'BALAZ S');
fides_INSERT INTO athletes VALUES ('724', 'BALAZOVA Barbora', 'BALAZOVA B');
fides_INSERT INTO athletes VALUES ('725', 'BALDASSARRI Milena', 'BALDASSARRI M');
fides_INSERT INTO athletes VALUES ('726', 'BALDUCCINI Stephanie', 'BALDUCCINI S');
fides_INSERT INTO athletes VALUES ('727', 'BALDWIN Roldani', 'BALDWIN R');
fides_INSERT INTO athletes VALUES ('728', 'BALEISYTE Olivija', 'BALEISYTE O');
fides_INSERT INTO athletes VALUES ('729', 'BALEIWAIRIKI Iosefo Masikau', 'BALEIWAIRIKI IM');
fides_INSERT INTO athletes VALUES ('730', 'BALEW Birhanu', 'BALEW B');
fides_INSERT INTO athletes VALUES ('731', 'BALK Lars', 'BALK L');
fides_INSERT INTO athletes VALUES ('732', 'BALKAN Onur', 'BALKAN O');
fides_INSERT INTO athletes VALUES ('733', 'BALLA Virag', 'BALLA V');
fides_INSERT INTO athletes VALUES ('734', 'BALLEZA ISAIAS Jose', 'BALLEZA ISAIAS J');
fides_INSERT INTO athletes VALUES ('735', 'BALLO Stefano', 'BALLO S');
fides_INSERT INTO athletes VALUES ('736', 'BALMACEDA Rosario', 'BALMACEDA R');
fides_INSERT INTO athletes VALUES ('737', 'BALOGH Matyas Laszlo', 'BALOGH ML');
fides_INSERT INTO athletes VALUES ('738', 'BALOGUN Elizabeth', 'BALOGUN E');
fides_INSERT INTO athletes VALUES ('739', 'BALOYES Bernardo', 'BALOYES B');
fides_INSERT INTO athletes VALUES ('740', 'BALSAMO Elisa', 'BALSAMO E');
fides_INSERT INTO athletes VALUES ('741', 'BALSDON Grace', 'BALSDON G');
fides_INSERT INTO athletes VALUES ('742', 'BALSIGER Bryan', 'BALSIGER B');
fides_INSERT INTO athletes VALUES ('743', 'BALSINI Matin', 'BALSINI M');
fides_INSERT INTO athletes VALUES ('744', 'BALTA Ksenija', 'BALTA K');
fides_INSERT INTO athletes VALUES ('745', 'BALTACI Ozkan', 'BALTACI O');
fides_INSERT INTO athletes VALUES ('746', 'BALUTA Tudor', 'BALUTA T');
fides_INSERT INTO athletes VALUES ('747', 'BALVIN Ondrej', 'BALVIN O');
fides_INSERT INTO athletes VALUES ('748', 'BALZER Sara', 'BALZER S');
fides_INSERT INTO athletes VALUES ('749', 'BANDA Babra', 'BANDA B');
fides_INSERT INTO athletes VALUES ('750', 'BANDARENKA Vitali', 'BANDARENKA V');
fides_INSERT INTO athletes VALUES ('751', 'BANDO Yuta', 'BANDO Y');
fides_INSERT INTO athletes VALUES ('752', 'BANICEVIC Dusan', 'BANICEVIC D');
fides_INSERT INTO athletes VALUES ('753', 'BANN Blair Cameron', 'BANN BC');
fides_INSERT INTO athletes VALUES ('754', 'BANSLEY Heather', 'BANSLEY H');
fides_INSERT INTO athletes VALUES ('755', 'BANTI Caterina', 'BANTI C');
fides_INSERT INTO athletes VALUES ('756', 'BANUELOS Manuel', 'BANUELOS M');
fides_INSERT INTO athletes VALUES ('757', 'BANZERUK Ivan', 'BANZERUK I');
fides_INSERT INTO athletes VALUES ('758', 'BAO Shanju', 'BAO S');
fides_INSERT INTO athletes VALUES ('759', 'BAO Yingfeng', 'BAO Y');
fides_INSERT INTO athletes VALUES ('760', 'BAPTISTA Luisa', 'BAPTISTA L');
fides_INSERT INTO athletes VALUES ('761', 'BAPTISTA Messias', 'BAPTISTA M');
fides_INSERT INTO athletes VALUES ('762', 'BAPTISTE Kelly-Ann', 'BAPTISTE KA');
fides_INSERT INTO athletes VALUES ('763', 'BAQLAH Talita', 'BAQLAH T');
fides_INSERT INTO athletes VALUES ('764', 'BAQUERIZO McMILLAN Elsa', 'BAQUERIZO McMILLAN');
fides_INSERT INTO athletes VALUES ('765', 'BAR AM Noya', 'BAR AM N');
fides_INSERT INTO athletes VALUES ('766', 'BAR Juan Manuel', 'BAR JM');
fides_INSERT INTO athletes VALUES ('767', 'BARABANOV Mykyta', 'BARABANOV M');
fides_INSERT INTO athletes VALUES ('768', 'BARAKAT Hanna', 'BARAKAT H');
fides_INSERT INTO athletes VALUES ('769', 'BARANCHUK Anna', 'BARANCHUK A');
fides_INSERT INTO athletes VALUES ('770', 'BARANKOVA Denisa', 'BARANKOVA D');
fides_INSERT INTO athletes VALUES ('771', 'BARANOVA Varvara', 'BARANOVA V');
fides_INSERT INTO athletes VALUES ('772', 'BARANSKI Fabian', 'BARANSKI F');
fides_INSERT INTO athletes VALUES ('773', 'BARBACHAN Ana', 'BARBACHAN A');
fides_INSERT INTO athletes VALUES ('774', 'BARBANCON Morgan', 'BARBANCON M');
fides_INSERT INTO athletes VALUES ('775', 'BARBARA', 'BARBARA');
fides_INSERT INTO athletes VALUES ('776', 'BARBELIN Lisa', 'BARBELIN L');
fides_INSERT INTO athletes VALUES ('777', 'BARBER Kelsey-Lee', 'BARBER KL');
fides_INSERT INTO athletes VALUES ('778', 'BARBERENA MERCADO Edwin Orlando', 'BARBERENA MERCADO');
fides_INSERT INTO athletes VALUES ('779', 'BARBIERI Rachele', 'BARBIERI R');
fides_INSERT INTO athletes VALUES ('780', 'BARBOSA Eduardo', 'BARBOSA E');
fides_INSERT INTO athletes VALUES ('781', 'BARBOSA Kurt Bryan', 'BARBOSA KB');
fides_INSERT INTO athletes VALUES ('782', 'BARCELO MARTIN Paula', 'BARCELO MARTIN P');
fides_INSERT INTO athletes VALUES ('783', 'BARCO Esequiel', 'BARCO E');
fides_INSERT INTO athletes VALUES ('784', 'BARD Melvin', 'BARD M');
fides_INSERT INTO athletes VALUES ('785', 'BARDACH MARTIN Virginia', 'BARDACH MARTIN V');
fides_INSERT INTO athletes VALUES ('786', 'BARDENET Alexandre', 'BARDENET A');
fides_INSERT INTO athletes VALUES ('787', 'BARDI Felipe', 'BARDI F');
fides_INSERT INTO athletes VALUES ('788', 'BAREGA Selemon', 'BAREGA S');
fides_INSERT INTO athletes VALUES ('789', 'BARKER Elinor', 'BARKER E');
fides_INSERT INTO athletes VALUES ('790', 'BARNA Andrej', 'BARNA A');
fides_INSERT INTO athletes VALUES ('791', 'BARNES David', 'BARNES D');
fides_INSERT INTO athletes VALUES ('792', 'BARNES Emre Zafer', 'BARNES EZ');
fides_INSERT INTO athletes VALUES ('793', 'BARNES Nikole', 'BARNES N');
fides_INSERT INTO athletes VALUES ('794', 'BARNIAK Tomasz', 'BARNIAK T');
fides_INSERT INTO athletes VALUES ('795', 'BARONA Dominic', 'BARONA D');
fides_INSERT INTO athletes VALUES ('796', 'BARONETTO Santiago', 'BARONETTO S');
fides_INSERT INTO athletes VALUES ('797', 'BARR Thomas', 'BARR T');
fides_INSERT INTO athletes VALUES ('798', 'BARRAS Tom', 'BARRAS T');
fides_INSERT INTO athletes VALUES ('799', 'BARRATT Jordyn', 'BARRATT J');
fides_INSERT INTO athletes VALUES ('800', 'BARREDA Manuel', 'BARREDA M');
fides_INSERT INTO athletes VALUES ('801', 'BARRETT Danny', 'BARRETT D');
fides_INSERT INTO athletes VALUES ('802', 'BARRETT Stephanie', 'BARRETT S');
fides_INSERT INTO athletes VALUES ('803', 'BARRETTE Hugo', 'BARRETTE H');
fides_INSERT INTO athletes VALUES ('804', 'BARRETTO JUNIOR Francisco', 'BARRETTO JUNIOR F');
fides_INSERT INTO athletes VALUES ('805', 'BARRIE Margaret Vanessa', 'BARRIE MV');
fides_INSERT INTO athletes VALUES ('806', 'BARRIONUEVO Maria Noel', 'BARRIONUEVO MN');
fides_INSERT INTO athletes VALUES ('807', 'BARRIOS Anriquelis', 'BARRIOS A');
fides_INSERT INTO athletes VALUES ('808', 'BARRIOS NAVARRO Laura', 'BARRIOS NAVARRO L');
fides_INSERT INTO athletes VALUES ('809', 'BARRIOS Tomas', 'BARRIOS T');
fides_INSERT INTO athletes VALUES ('810', 'BARRONDO Bernardo Uriel', 'BARRONDO BU');
fides_INSERT INTO athletes VALUES ('811', 'BARRONDO Erick Bernabe', 'BARRONDO EB');
fides_INSERT INTO athletes VALUES ('812', 'BARRONDO Jose Alejandro', 'BARRONDO JA');
fides_INSERT INTO athletes VALUES ('813', 'BARROS Pedro', 'BARROS P');
fides_INSERT INTO athletes VALUES ('814', 'BARSEGHYAN Artur', 'BARSEGHYAN A');
fides_INSERT INTO athletes VALUES ('815', 'BARSHIM Mutaz Essa', 'BARSHIM ME');
fides_INSERT INTO athletes VALUES ('816', 'BART Adrien', 'BART A');
fides_INSERT INTO athletes VALUES ('817', 'BARTEKOVA Danka', 'BARTEKOVA D');
fides_INSERT INTO athletes VALUES ('818', 'BARTELSMEYER Amos', 'BARTELSMEYER A');
fides_INSERT INTO athletes VALUES ('819', 'BARTHA-KERI Bianka', 'BARTHA-KERI B');
fides_INSERT INTO athletes VALUES ('820', 'BARTHEL Danilo', 'BARTHEL D');
fides_INSERT INTO athletes VALUES ('821', 'BARTHEL Mona', 'BARTHEL M');
fides_INSERT INTO athletes VALUES ('822', 'BARTHEL Timo', 'BARTHEL T');
fides_INSERT INTO athletes VALUES ('823', 'BARTHELEMY Valerie', 'BARTHELEMY V');
fides_INSERT INTO athletes VALUES ('824', 'BARTLEY Karayme', 'BARTLEY K');
fides_INSERT INTO athletes VALUES ('825', 'BARTNIK Tomasz', 'BARTNIK T');
fides_INSERT INTO athletes VALUES ('826', 'BARTSCH-HACKLEY Michelle', 'BARTSCH-HACKLEY M');
fides_INSERT INTO athletes VALUES ('827', 'BARTY Ashleigh', 'BARTY A');
fides_INSERT INTO athletes VALUES ('828', 'BARU Morea', 'BARU M');
fides_INSERT INTO athletes VALUES ('829', 'BARYARD-JOHNSSON Malin', 'BARYARD-JOHNSSON M');
fides_INSERT INTO athletes VALUES ('830', 'BARZELAY Aviv', 'BARZELAY A');
fides_INSERT INTO athletes VALUES ('831', 'BASHAEV Tamerlan', 'BASHAEV T');
fides_INSERT INTO athletes VALUES ('832', 'BASHIR Ghulam Mustafa', 'BASHIR GM');
fides_INSERT INTO athletes VALUES ('833', 'BASHTA Anna', 'BASHTA A');
fides_INSERT INTO athletes VALUES ('834', 'BASIC Hana', 'BASIC H');
fides_INSERT INTO athletes VALUES ('835', 'BASILASHVILI Nikoloz', 'BASILASHVILI N');
fides_INSERT INTO athletes VALUES ('836', 'BASILE Fabio', 'BASILE F');
fides_INSERT INTO athletes VALUES ('837', 'BASOVA Liubov', 'BASOVA L');
fides_INSERT INTO athletes VALUES ('838', 'BASS Gina', 'BASS G');
fides_INSERT INTO athletes VALUES ('839', 'BASSETO Guilherme', 'BASSETO G');
fides_INSERT INTO athletes VALUES ('840', 'BASSIL Ray', 'BASSIL R');
fides_INSERT INTO athletes VALUES ('841', 'BASTERRA Jose Maria', 'BASTERRA JM');
fides_INSERT INTO athletes VALUES ('842', 'BASTIAN Izaak', 'BASTIAN I');
fides_INSERT INTO athletes VALUES ('843', 'BASTIANELLI Marta', 'BASTIANELLI M');
fides_INSERT INTO athletes VALUES ('844', 'BASTIEN Steven', 'BASTIEN S');
fides_INSERT INTO athletes VALUES ('845', 'BAT OCHIR Bolortuya', 'BAT OCHIR B');
fides_INSERT INTO athletes VALUES ('846', 'BATASHOVA Uliana', 'BATASHOVA U');
fides_INSERT INTO athletes VALUES ('847', 'BATBAYAR Enkhkhuslen', 'BATBAYAR E');
fides_INSERT INTO athletes VALUES ('848', 'BATEMAN Amanda', 'BATEMAN A');
fides_INSERT INTO athletes VALUES ('849', 'BATINI Martina', 'BATINI M');
fides_INSERT INTO athletes VALUES ('850', 'BATIRMURZAEV Yusup', 'BATIRMURZAEV Y');
fides_INSERT INTO athletes VALUES ('851', 'BATISTA Ketiley', 'BATISTA K');
fides_INSERT INTO athletes VALUES ('852', 'BATIVAKALOLO Raichel', 'BATIVAKALOLO R');
fides_INSERT INTO athletes VALUES ('853', 'BATKI Noemi', 'BATKI N');
fides_INSERT INTO athletes VALUES ('854', 'BATMUNKH Bolorerdene', 'BATMUNKH B');
fides_INSERT INTO athletes VALUES ('855', 'BAT-OCHIR Ser-Od', 'BAT-OCHIR SO');
fides_INSERT INTO athletes VALUES ('856', 'BATRA Manika', 'BATRA M');
fides_INSERT INTO athletes VALUES ('857', 'BATSARASHKINA Vitalina', 'BATSARASHKINA V');
fides_INSERT INTO athletes VALUES ('858', 'BATTAI Sugar Katinka', 'BATTAI SK');
fides_INSERT INTO athletes VALUES ('859', 'BATT-DOYLE Isobel', 'BATT-DOYLE I');
fides_INSERT INTO athletes VALUES ('860', 'BATTEN Haley', 'BATTEN H');
fides_INSERT INTO athletes VALUES ('861', 'BATTISTON Michela', 'BATTISTON M');
fides_INSERT INTO athletes VALUES ('862', 'BATTLE Anavia', 'BATTLE A');
fides_INSERT INTO athletes VALUES ('863', 'BATTOCLETTI Nadia', 'BATTOCLETTI N');
fides_INSERT INTO athletes VALUES ('864', 'BATUM Nicolas', 'BATUM N');
fides_INSERT INTO athletes VALUES ('865', 'BATUROV Bobo-Usmon', 'BATUROV B');
fides_INSERT INTO athletes VALUES ('866', 'BATYRGAZIEV Albert', 'BATYRGAZIEV A');
fides_INSERT INTO athletes VALUES ('867', 'BATYRSHINA Zilia', 'BATYRSHINA Z');
fides_INSERT INTO athletes VALUES ('868', 'BAU Martin', 'BAU M');
fides_INSERT INTO athletes VALUES ('869', 'BAUMANN Christian', 'BAUMANN C');
fides_INSERT INTO athletes VALUES ('870', 'BAUMGART-WITAN Iga', 'BAUMGART-WITAN I');
fides_INSERT INTO athletes VALUES ('871', 'BAUTISTA Jose', 'BAUTISTA J');
fides_INSERT INTO athletes VALUES ('872', 'BAYARTSOGT Munkhzaya', 'BAYARTSOGT M');
fides_INSERT INTO athletes VALUES ('873', 'BAYASGALAN Solongo', 'BAYASGALAN S');
fides_INSERT INTO athletes VALUES ('874', 'BAYNES Aron', 'BAYNES A');
fides_INSERT INTO athletes VALUES ('875', 'BAYRAMOV Turan', 'BAYRAMOV T');
fides_INSERT INTO athletes VALUES ('876', 'BAZ Shane', 'BAZ S');
fides_INSERT INTO athletes VALUES ('877', 'BAZADZE Sandro', 'BAZADZE S');
fides_INSERT INTO athletes VALUES ('878', 'BAZAN VELEZ Lautaro', 'BAZAN VELEZ L');
fides_INSERT INTO athletes VALUES ('879', 'BAZARZHAPOV Galsan', 'BAZARZHAPOV G');
fides_INSERT INTO athletes VALUES ('880', 'BAZO GERMAN Maria Belen', 'BAZO GERMAN MB');
fides_INSERT INTO athletes VALUES ('881', 'BAZOLO Lorene Dorcas', 'BAZOLO LD');
fides_INSERT INTO athletes VALUES ('882', 'BEALE Daniel James', 'BEALE DJ');
fides_INSERT INTO athletes VALUES ('883', 'BEATRIZ', 'BEATRIZ');
fides_INSERT INTO athletes VALUES ('884', 'BEAUCHEMIN-PINARD Catherine', 'BEAUCHEMIN-PINARD');
fides_INSERT INTO athletes VALUES ('885', 'BEAUGRAND Cassandre', 'BEAUGRAND C');
fides_INSERT INTO athletes VALUES ('886', 'BEAUMONT Jack', 'BEAUMONT J');
fides_INSERT INTO athletes VALUES ('887', 'BEAUMONT Maxime', 'BEAUMONT M');
fides_INSERT INTO athletes VALUES ('888', 'BEBENDORF Karl', 'BEBENDORF K');
fides_INSERT INTO athletes VALUES ('889', 'BECCARO Luca', 'BECCARO L');
fides_INSERT INTO athletes VALUES ('890', 'BECHDEJU Laura', 'BECHDEJU L');
fides_INSERT INTO athletes VALUES ('891', 'BECK Alex', 'BECK A');
fides_INSERT INTO athletes VALUES ('892', 'BECK Leonie', 'BECK L');
fides_INSERT INTO athletes VALUES ('893', 'BECKER Bowen', 'BECKER B');
fides_INSERT INTO athletes VALUES ('894', 'BECKER Charlotte', 'BECKER C');
fides_INSERT INTO athletes VALUES ('895', 'BECKER Sophie', 'BECKER S');
fides_INSERT INTO athletes VALUES ('896', 'BECKIE Janine', 'BECKIE J');
fides_INSERT INTO athletes VALUES ('897', 'BECKMANN Emilie', 'BECKMANN E');
fides_INSERT INTO athletes VALUES ('898', 'BEDDOES Alex', 'BEDDOES A');
fides_INSERT INTO athletes VALUES ('899', 'BEDNARCZUK Agatha', 'BEDNARCZUK A');
fides_INSERT INTO athletes VALUES ('900', 'BEDNAREK Kenneth', 'BEDNAREK K');
fides_INSERT INTO athletes VALUES ('901', 'BEDRANI Djilali', 'BEDRANI D');
fides_INSERT INTO athletes VALUES ('902', 'BEER Ellie', 'BEER E');
fides_INSERT INTO athletes VALUES ('903', 'BEER Jolyn', 'BEER J');
fides_INSERT INTO athletes VALUES ('904', 'BEERENSTEYN Lineth', 'BEERENSTEYN L');
fides_INSERT INTO athletes VALUES ('905', 'BEESLEY Meghan', 'BEESLEY M');
fides_INSERT INTO athletes VALUES ('906', 'BEIGI HARCHEGANI Milad', 'BEIGI HARCHEGANI M');
fides_INSERT INTO athletes VALUES ('907', 'BEJAN Sergiu', 'BEJAN S');
fides_INSERT INTO athletes VALUES ('908', 'BEJINARIU Viviana', 'BEJINARIU V');
fides_INSERT INTO athletes VALUES ('909', 'BEKA BEKA Alexis', 'BEKA BEKA A');
fides_INSERT INTO athletes VALUES ('910', 'BEKAURI Lasha', 'BEKAURI L');
fides_INSERT INTO athletes VALUES ('911', 'BEKE Kornel', 'BEKE K');
fides_INSERT INTO athletes VALUES ('912', 'BEKELE Alemu', 'BEKELE A');
fides_INSERT INTO athletes VALUES ('913', 'BEKESI Eszter', 'BEKESI E');
fides_INSERT INTO athletes VALUES ('914', 'BEKHAZI Joelle', 'BEKHAZI J');
fides_INSERT INTO athletes VALUES ('915', 'BEKH-ROMANCHUK Maryna', 'BEKH-ROMANCHUK M');
fides_INSERT INTO athletes VALUES ('916', 'BEKKERING Annemiek', 'BEKKERING A');
fides_INSERT INTO athletes VALUES ('917', 'BEKKERING Ross', 'BEKKERING R');
fides_INSERT INTO athletes VALUES ('918', 'BEKMEZ Meryem', 'BEKMEZ M');
fides_INSERT INTO athletes VALUES ('919', 'BEL AHBIB Oumayma', 'BEL AHBIB O');
fides_INSERT INTO athletes VALUES ('920', 'BELAUD Valentin', 'BELAUD V');
fides_INSERT INTO athletes VALUES ('921', 'BELCHER Mathew', 'BELCHER M');
fides_INSERT INTO athletes VALUES ('922', 'BELEAGA Gianina', 'BELEAGA G');
fides_INSERT INTO athletes VALUES ('923', 'BELEMU Margaret', 'BELEMU M');
fides_INSERT INTO athletes VALUES ('924', 'BELENIUK Zhan', 'BELENIUK Z');
fides_INSERT INTO athletes VALUES ('925', 'BELETEW Yehualeye', 'BELETEW Y');
fides_INSERT INTO athletes VALUES ('926', 'BELINSKA Alla', 'BELINSKA A');
fides_INSERT INTO athletes VALUES ('927', 'BELJAJEVA Julia', 'BELJAJEVA J');
fides_INSERT INTO athletes VALUES ('928', 'BELL Alexandra', 'BELL A');
fides_INSERT INTO athletes VALUES ('929', 'BELL Daniel', 'BELL D');
fides_INSERT INTO athletes VALUES ('930', 'BELL Joe', 'BELL J');
fides_INSERT INTO athletes VALUES ('931', 'BELLANDI Alice', 'BELLANDI A');
fides_INSERT INTO athletes VALUES ('932', 'BELLE Tia-Adana', 'BELLE TA');
fides_INSERT INTO athletes VALUES ('933', 'BELLIO Katrina', 'BELLIO K');
fides_INSERT INTO athletes VALUES ('934', 'BELLO Ayomide Emmanuel', 'BELLO AE');
fides_INSERT INTO athletes VALUES ('935', 'BELLO Elena', 'BELLO E');
fides_INSERT INTO athletes VALUES ('936', 'BELMONTE Mireia', 'BELMONTE M');
fides_INSERT INTO athletes VALUES ('937', 'BELMONTE Tomas', 'BELMONTE T');
fides_INSERT INTO athletes VALUES ('938', 'BELO Francisco', 'BELO F');
fides_INSERT INTO athletes VALUES ('939', 'BELOCIAN Wilhem', 'BELOCIAN W');
fides_INSERT INTO athletes VALUES ('940', 'BELOMOINA Yana', 'BELOMOINA Y');
fides_INSERT INTO athletes VALUES ('941', 'BELTRAN Fernando', 'BELTRAN F');
fides_INSERT INTO athletes VALUES ('942', 'BELTRAN MIR Albert', 'BELTRAN MIR A');
fides_INSERT INTO athletes VALUES ('943', 'BELTZ Joshua', 'BELTZ J');
fides_INSERT INTO athletes VALUES ('944', 'BELYAVSKIY David', 'BELYAVSKIY D');
fides_INSERT INTO athletes VALUES ('945', 'BEN Adrian', 'BEN A');
fides_INSERT INTO athletes VALUES ('946', 'BEN AZIZI Nadia', 'BEN AZIZI N');
fides_INSERT INTO athletes VALUES ('947', 'BEN CHAABANE Amira', 'BEN CHAABANE A');
fides_INSERT INTO athletes VALUES ('948', 'BEN CHEIKH Mehdi', 'BEN CHEIKH M');
fides_INSERT INTO athletes VALUES ('949', 'BEN HNIA Karem', 'BEN HNIA K');
fides_INSERT INTO athletes VALUES ('950', 'BEN ISMAIL Afef', 'BEN ISMAIL A');
fides_INSERT INTO athletes VALUES ('951', 'BEN OTHMEN MILADI Mohamed Ali', 'BEN OTHMEN MILADI');
fides_INSERT INTO athletes VALUES ('952', 'BEN SLIMENE Khaled', 'BEN SLIMENE K');
fides_INSERT INTO athletes VALUES ('953', 'BEN TARA Wassim', 'BEN TARA W');
fides_INSERT INTO athletes VALUES ('954', 'BEN YESSOUF Tekiath', 'BEN YESSOUF T');
fides_INSERT INTO athletes VALUES ('955', 'BEN ZAHRA Abdelkarim', 'BEN ZAHRA A');
fides_INSERT INTO athletes VALUES ('956', 'BENARD Chris', 'BENARD C');
fides_INSERT INTO athletes VALUES ('957', 'BENATI Lorenzo', 'BENATI L');
fides_INSERT INTO athletes VALUES ('958', 'BENCHABLA Abdelhafid', 'BENCHABLA A');
fides_INSERT INTO athletes VALUES ('959', 'BENCIC Belinda', 'BENCIC B');
fides_INSERT INTO athletes VALUES ('960', 'BENEDETTI Julia', 'BENEDETTI J');
fides_INSERT INTO athletes VALUES ('961', 'BENEGAS Perris', 'BENEGAS P');
fides_INSERT INTO athletes VALUES ('962', 'BENFEITO Meaghan', 'BENFEITO M');
fides_INSERT INTO athletes VALUES ('963', 'BENFERDJALLAH Fateh', 'BENFERDJALLAH F');
fides_INSERT INTO athletes VALUES ('964', 'BENGTSSON Angelica', 'BENGTSSON A');
fides_INSERT INTO athletes VALUES ('965', 'BENGTSSON Rolf-Goran', 'BENGTSSON RG');
fides_INSERT INTO athletes VALUES ('966', 'BENGUCHE Jorge', 'BENGUCHE J');
fides_INSERT INTO athletes VALUES ('967', 'BENHADJA Loubna', 'BENHADJA L');
fides_INSERT INTO athletes VALUES ('968', 'BENITES Bruna', 'BENITES B');
fides_INSERT INTO athletes VALUES ('969', 'BENITEZ Andrea', 'BENITEZ A');
fides_INSERT INTO athletes VALUES ('970', 'BENITEZ Jackie', 'BENITEZ J');
fides_INSERT INTO athletes VALUES ('971', 'BENJAMIN Kion', 'BENJAMIN K');
fides_INSERT INTO athletes VALUES ('972', 'BENJAMIN Rai', 'BENJAMIN R');
fides_INSERT INTO athletes VALUES ('973', 'BENN Britt', 'BENN B');
fides_INSERT INTO athletes VALUES ('974', 'BENNAMA Billal', 'BENNAMA B');
fides_INSERT INTO athletes VALUES ('975', 'BENNETT George', 'BENNETT G');
fides_INSERT INTO athletes VALUES ('976', 'BENNETT Karen', 'BENNETT K');
fides_INSERT INTO athletes VALUES ('977', 'BENNISON Hanna', 'BENNISON H');
fides_INSERT INTO athletes VALUES ('978', 'BENOOT Tiesj', 'BENOOT T');
fides_INSERT INTO athletes VALUES ('979', 'BENTZ Gunnar', 'BENTZ G');
fides_INSERT INTO athletes VALUES ('980', 'BENUS Matej', 'BENUS M');
fides_INSERT INTO athletes VALUES ('981', 'BENZING Robin', 'BENZING R');
fides_INSERT INTO athletes VALUES ('982', 'BERARIU Stefan', 'BERARIU S');
fides_INSERT INTO athletes VALUES ('983', 'BERDER Cecilia', 'BERDER C');
fides_INSERT INTO athletes VALUES ('984', 'BERDIMURATOV Jalgasbay', 'BERDIMURATOV J');
fides_INSERT INTO athletes VALUES ('985', 'BERECZ Zsombor', 'BERECZ Z');
fides_INSERT INTO athletes VALUES ('986', 'BERENGUER Ignacio', 'BERENGUER I');
fides_INSERT INTO athletes VALUES ('987', 'BERES Amalia', 'BERES A');
fides_INSERT INTO athletes VALUES ('988', 'BERES Madalina', 'BERES M');
fides_INSERT INTO athletes VALUES ('989', 'BERGER Eline', 'BERGER E');
fides_INSERT INTO athletes VALUES ('990', 'BERGER Eva', 'BERGER E');
fides_INSERT INTO athletes VALUES ('991', 'BERGER Matt', 'BERGER M');
fides_INSERT INTO athletes VALUES ('992', 'BERGERE Leo', 'BERGERE L');
fides_INSERT INTO athletes VALUES ('993', 'BERGERUD Torbjoern', 'BERGERUD T');
fides_INSERT INTO athletes VALUES ('994', 'BERGLUND Kalle', 'BERGLUND K');
fides_INSERT INTO athletes VALUES ('995', 'BERGSTROEM Linda', 'BERGSTROEM L');
fides_INSERT INTO athletes VALUES ('996', 'BERGSTROM Fredrik', 'BERGSTROM F');
fides_INSERT INTO athletes VALUES ('997', 'BERGSTROM Olivia', 'BERGSTROM O');
fides_INSERT INTO athletes VALUES ('998', 'BERKHOUT Lobke', 'BERKHOUT L');
fides_INSERT INTO athletes VALUES ('999', 'BERLIN REYES Kevin', 'BERLIN REYES K');
fides_INSERT INTO athletes VALUES ('1000', 'BERNA Phil', 'BERNA P');